package lissa.be;
// Generated 20/06/2018 10:45:36 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AjusteInventario generated by hbm2java
 */
public class AjusteInventario  implements java.io.Serializable {


     private long idajusteinventario;
     private AlmacenProducto almacenProducto;
     private String motivoAjuste;
     private double stockActual;
     private double stockFisico;
     private Date fechaAjuste;
     private Long idUser;

    public AjusteInventario() {
    }

	
   
    public long getIdajusteinventario() {
        return this.idajusteinventario;
    }
    
    public void setIdajusteinventario(long idajusteinventario) {
        this.idajusteinventario = idajusteinventario;
    }
    public AlmacenProducto getAlmacenProducto() {
        return this.almacenProducto;
    }
    
    public void setAlmacenProducto(AlmacenProducto almacenProducto) {
        this.almacenProducto = almacenProducto;
    }
    public String getMotivoAjuste() {
        return this.motivoAjuste;
    }
    
    public void setMotivoAjuste(String motivoAjuste) {
        this.motivoAjuste = motivoAjuste;
    }
    public double getStockActual() {
        return this.stockActual;
    }
    
    public void setStockActual(double stockActual) {
        this.stockActual = stockActual;
    }
    public double getStockFisico() {
        return this.stockFisico;
    }
    
    public void setStockFisico(double stockFisico) {
        this.stockFisico = stockFisico;
    }
    public Date getFechaAjuste() {
        return this.fechaAjuste;
    }
    
    public void setFechaAjuste(Date fechaAjuste) {
        this.fechaAjuste = fechaAjuste;
    }
    public Long getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Long idUser) {
        this.idUser = idUser;
    }




}


