package lissa.be;
// Generated 19/04/2018 04:37:19 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AlmacenProducto generated by hbm2java
 */
public class AlmacenProducto  implements java.io.Serializable {
  
     private long idalmacenproducto;
     private Almacen almacen;
     private Producto producto;
     private BigDecimal stockActual;
     private Date fechaRegistro;
     private Date fechaUltAct;
     private String lote;
     private Date fechaVencimiento;     
     private boolean estado;
     private BigDecimal valorCompraUnitario;
     private BigDecimal PrecioCompraUnitario;
     private Integer ordenRegistro;
     private Set<PrecioProducto> precioProductos = new HashSet<PrecioProducto>(0);
     private Set<AjusteInventario> ajusteInventarios = new HashSet<AjusteInventario>(0);

    public AlmacenProducto() {
    }
    
    public long getIdalmacenproducto() {
        return this.idalmacenproducto;
    }
    
    public void setIdalmacenproducto(long idalmacenproducto) {
        this.idalmacenproducto = idalmacenproducto;
    }
    public Almacen getAlmacen() {
        return this.almacen;
    }
    
    public void setAlmacen(Almacen almacen) {
        this.almacen = almacen;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public BigDecimal getStockActual() {
        return this.stockActual;
    }
    
    public void setStockActual(BigDecimal stockActual) {
        this.stockActual = stockActual;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaUltAct() {
        return this.fechaUltAct;
    }
    
    public void setFechaUltAct(Date fechaUltAct) {
        this.fechaUltAct = fechaUltAct;
    }
    public String getLote() {
        return this.lote;
    }
    
    public void setLote(String lote) {
        this.lote = lote;
    }
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }
   
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public BigDecimal getValorCompraUnitario() {
        return this.valorCompraUnitario;
    }
    
    public void setValorCompraUnitario(BigDecimal valorCompraUnitario) {
        this.valorCompraUnitario = valorCompraUnitario;
    }
    public Integer getOrdenRegistro() {
        return this.ordenRegistro;
    }
    
    public void setOrdenRegistro(Integer ordenRegistro) {
        this.ordenRegistro = ordenRegistro;
    }
    public Set<PrecioProducto> getPrecioProductos() {
        return this.precioProductos;
    }
    
    public void setPrecioProductos(Set<PrecioProducto> precioProductos) {
        this.precioProductos = precioProductos;
    }

    public Set<AjusteInventario> getAjusteInventarios() {
        return ajusteInventarios;
    }

    public void setAjusteInventarios(Set<AjusteInventario> ajusteInventarios) {
        this.ajusteInventarios = ajusteInventarios;
    }


     public BigDecimal getPrecioCompraUnitario() {
        return PrecioCompraUnitario;
    }

    public void setPrecioCompraUnitario(BigDecimal PrecioCompraUnitario) {
        this.PrecioCompraUnitario = PrecioCompraUnitario;
    }

}


