package lissa.be;
// Generated 23-sep-2016 12:43:58 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;


/**
 * Almacen generated by hbm2java
 */
public class Almacen implements java.io.Serializable {

    private long idalmacen;
    private String nombre;
    private Set<AlmacenProducto> almacenProductos = new HashSet<AlmacenProducto>(0);
    private Set<Kardex> kardexesForIdOrigen = new HashSet<Kardex>(0);
    private Set<Kardex> kardexesForIdDestino = new HashSet<Kardex>(0);
    public static final int DEFECTO = 1, DATO = 3;
    private int op = -1;

    public Almacen() {
    }

    

    public long getIdalmacen() {
        return this.idalmacen;
    }

    public void setIdalmacen(long idalmacen) {
        this.idalmacen = idalmacen;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Set<AlmacenProducto> getAlmacenProductos() {
        return this.almacenProductos;
    }

    public void setAlmacenProductos(Set<AlmacenProducto> almacenProductos) {
        this.almacenProductos = almacenProductos;
    }

    public Set<Kardex> getKardexesForIdOrigen() {
        return this.kardexesForIdOrigen;
    }

    public void setKardexesForIdOrigen(Set<Kardex> kardexesForIdOrigen) {
        this.kardexesForIdOrigen = kardexesForIdOrigen;
    }

    public Set<Kardex> getKardexesForIdDestino() {
        return this.kardexesForIdDestino;
    }

    public void setKardexesForIdDestino(Set<Kardex> kardexesForIdDestino) {
        this.kardexesForIdDestino = kardexesForIdDestino;
    }

   public int getOp() {
        return op;
    }

    public void setOp(int op) {
        this.op = op;
    }
    
    @Override
    public String toString() {
        switch (op) {
            case DATO:
                return getNombre();
            default:
                return "<Seleccione>";
        }
    }
    
}
