package lissa.be;
// Generated 10-dic-2016 10:56:26 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * FarComprobante generated by hbm2java
 */
public class AreaConsumo implements java.io.Serializable {

    private long idareaconsumo;
    private String descripcion;
    private Set<Venta> ventas = new HashSet<Venta>(0);

    private int op = -1;
    public static final int DEFECTO = -1, DATO = 3;

    public AreaConsumo() {
    }



   

    public Set<Venta> getVentas() {
        return this.ventas;
    }

    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }


    @Override
    public String toString() {
        switch (getOp()) {
            case DATO:
                return getDescripcion();
            default:
                return "<Seleccione>";
        }
    }

    public int getOp() {
        return op;
    }

    public void setOp(int op) {
        this.op = op;
    }

    public long getIdareaconsumo() {
        return idareaconsumo;
    }

    public void setIdareaconsumo(long idareaconsumo) {
        this.idareaconsumo = idareaconsumo;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

}
