package lissa.be;
// Generated 07-dic-2016 10:43:52 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * AreaCaja generated by hbm2java
 */
public class AreaCaja implements java.io.Serializable {

    private long idareacaja;
    private String modulo;
    private boolean estado;
    private Set<Caja> cajas = new HashSet<Caja>(0);

    private int op = -1;
    public static final int DEFECTO = -1, DATO = 3;

    public AreaCaja() {
    }

    public long getIdareacaja() {
        return this.idareacaja;
    }

    public void setIdareacaja(long idareacaja) {
        this.idareacaja = idareacaja;
    }

    public String getModulo() {
        return this.modulo;
    }

    public void setModulo(String modulo) {
        this.modulo = modulo;
    }

    public boolean isEstado() {
        return this.estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    public Set<Caja> getCajas() {
        return this.cajas;
    }

    public void setCajas(Set<Caja> cajas) {
        this.cajas = cajas;
    }
    
    public int getOp() {
        return op;
    }

    public void setOp(int op) {
        this.op = op;
    }
    
    @Override
    public String toString() {
        switch (getOp()) {
            case DATO:
                return getModulo();
            default:
                return "<SELECCIONE>";
        }
    }
}
