package lissa.be;
// Generated 19/09/2018 05:49:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Atencionhc generated by hbm2java
 */
public class Atencionhc  implements java.io.Serializable {


     private long idatencionhc;
     private HistoriaClinica historiaClinica;
     private Date fechaAtencion;
     private String horaAtencion;
     private Integer edad;
     private String tipoAtencion;
     private long idUsuarioEnf;
     private long idUsuarioMed;
     private Set<FuncionVital> funcionVitals = new HashSet<FuncionVital>(0);

    public Atencionhc() {
    }

	
    public Atencionhc(long idatencionhc, HistoriaClinica historiaClinica, Date fechaAtencion) {
        this.idatencionhc = idatencionhc;
        this.historiaClinica = historiaClinica;
        this.fechaAtencion = fechaAtencion;
    }
    
   
    public long getIdatencionhc() {
        return this.idatencionhc;
    }
    
    public void setIdatencionhc(long idatencionhc) {
        this.idatencionhc = idatencionhc;
    }
    public HistoriaClinica getHistoriaClinica() {
        return this.historiaClinica;
    }
    
    public void setHistoriaClinica(HistoriaClinica historiaClinica) {
        this.historiaClinica = historiaClinica;
    }
    public Date getFechaAtencion() {
        return this.fechaAtencion;
    }
    
    public void setFechaAtencion(Date fechaAtencion) {
        this.fechaAtencion = fechaAtencion;
    }
    public String getHoraAtencion() {
        return this.horaAtencion;
    }
    
    public void setHoraAtencion(String horaAtencion) {
        this.horaAtencion = horaAtencion;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public String getTipoAtencion() {
        return this.tipoAtencion;
    }
    
    public void setTipoAtencion(String tipoAtencion) {
        this.tipoAtencion = tipoAtencion;
    }
    public long getIdUsuarioEnf() {
        return this.idUsuarioEnf;
    }
    
    public void setIdUsuarioEnf(long idUsuarioEnf) {
        this.idUsuarioEnf = idUsuarioEnf;
    }
    public long getIdUsuarioMed() {
        return this.idUsuarioMed;
    }
    
    public void setIdUsuarioMed(long idUsuarioMed) {
        this.idUsuarioMed = idUsuarioMed;
    }
   
    public Set<FuncionVital> getFuncionVitals() {
        return this.funcionVitals;
    }
    
    public void setFuncionVitals(Set<FuncionVital> funcionVitals) {
        this.funcionVitals = funcionVitals;
    }
    

}


