package lissa.be;
// Generated 19/09/2018 03:22:57 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Atencion generated by hbm2java
 */
public class Atencion implements java.io.Serializable {

    private long idatencion;
    private Persona persona;
    private Cita cita;
    private Date fechaIngreso;
    private Integer numeroAtencion;
    private String tipoIngreso;
    private HistoriaClinica historiaClinica;
    private Long idUseradmision;
    private Long idUsertriaje;
    private String estado;
    private String tipoPaciente;
    private Integer edad;
    private Set<Comprobante> comprobantes = new HashSet<Comprobante>(0);

    public Atencion() {
    }

    public Atencion(long idatencion, Persona persona, Date fechaIngreso) {
        this.idatencion = idatencion;
        this.persona = persona;
        this.fechaIngreso = fechaIngreso;
    }

    public long getIdatencion() {
        return this.idatencion;
    }

    public void setIdatencion(long idatencion) {
        this.idatencion = idatencion;
    }

    public Persona getPersona() {
        return this.persona;
    }

    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }

    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    public Integer getNumeroAtencion() {
        return this.numeroAtencion;
    }

    public void setNumeroAtencion(Integer numeroAtencion) {
        this.numeroAtencion = numeroAtencion;
    }

    public String getTipoIngreso() {
        return this.tipoIngreso;
    }

    public void setTipoIngreso(String tipoIngreso) {
        this.tipoIngreso = tipoIngreso;
    }

    public Long getIdUseradmision() {
        return this.idUseradmision;
    }

    public void setIdUseradmision(Long idUseradmision) {
        this.idUseradmision = idUseradmision;
    }

    public Long getIdUsertriaje() {
        return this.idUsertriaje;
    }

    public void setIdUsertriaje(Long idUsertriaje) {
        this.idUsertriaje = idUsertriaje;
    }

    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public Set<Comprobante> getComprobantes() {
        return this.comprobantes;
    }

    public void setComprobantes(Set<Comprobante> comprobantes) {
        this.comprobantes = comprobantes;
    }

    public String getTipoPaciente() {
        return tipoPaciente;
    }

    public void setTipoPaciente(String tipoPaciente) {
        this.tipoPaciente = tipoPaciente;
    }

    public Integer getEdad() {
        return edad;
    }

    public void setEdad(Integer edad) {
        this.edad = edad;
    }

    public HistoriaClinica getHistoriaClinica() {
        return historiaClinica;
    }

    public void setHistoriaClinica(HistoriaClinica historiaClinica) {
        this.historiaClinica = historiaClinica;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 89 * hash + Objects.hashCode(this.numeroAtencion);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Atencion other = (Atencion) obj;
        if (!Objects.equals(this.numeroAtencion, other.numeroAtencion)) {
            return false;
        }
        return true;
    }

    public Cita getCita() {
        return cita;
    }

    public void setCita(Cita cita) {
        this.cita = cita;
    }
}
