package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Beneficio generated by hbm2java
 */
public class Beneficio implements java.io.Serializable {

    private int idbeneficio;
    private SeguroVida seguroVida;
    private String nombreBeneficio;
    private Boolean estado;
    private int porcCubierto;
    
    private Set<ComprobanteDetalle> itemsComprobantes = new HashSet<ComprobanteDetalle>(0);
    private Set<Comprobante> comprobantes = new HashSet<Comprobante>(0);
    public static final int DEFECTO = -1, DATO = 3;
    private int op = -1;

    public Beneficio() {
    }

    public Beneficio(int idbeneficio, SeguroVida seguroVida) {
        this.idbeneficio = idbeneficio;
        this.seguroVida = seguroVida;
    }

    public Beneficio(int idbeneficio, SeguroVida seguroVida, String nombreBeneficio, Boolean estado, Set<ComprobanteDetalle> itemsComprobantes, Set<Comprobante> comprobantes) {
        this.idbeneficio = idbeneficio;
        this.seguroVida = seguroVida;
        this.nombreBeneficio = nombreBeneficio;
        this.estado = estado;
        this.itemsComprobantes = itemsComprobantes;
        this.comprobantes = comprobantes;
    }

    public int getIdbeneficio() {
        return this.idbeneficio;
    }

    public void setIdbeneficio(int idbeneficio) {
        this.idbeneficio = idbeneficio;
    }

    public SeguroVida getSeguroVida() {
        return this.seguroVida;
    }

    public void setSeguroVida(SeguroVida seguroVida) {
        this.seguroVida = seguroVida;
    }

    public String getNombreBeneficio() {
        return this.nombreBeneficio;
    }

    public void setNombreBeneficio(String nombreBeneficio) {
        this.nombreBeneficio = nombreBeneficio;
    }

    public Boolean getEstado() {
        return this.estado;
    }

    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    public Set<ComprobanteDetalle> getItemsComprobantes() {
        return this.itemsComprobantes;
    }

    public void setItemsComprobantes(Set<ComprobanteDetalle> itemsComprobantes) {
        this.itemsComprobantes = itemsComprobantes;
    }

    public Set<Comprobante> getComprobantes() {
        return this.comprobantes;
    }

    public void setComprobantes(Set<Comprobante> comprobantes) {
        this.comprobantes = comprobantes;
    }
    
    
    public int getPorcCubierto() {
        return porcCubierto;
    }

    public void setPorcCubierto(int porcCubierto) {
        this.porcCubierto = porcCubierto;
    }

    public int getOp() {
        return op;
    }

    public void setOp(int op) {
        this.op = op;
    }

    @Override
    public String toString() {
        switch (op) {
            case DATO:
                return getNombreBeneficio();
            default:
                return "<SELECCIONE>";
        }
    }

}
