package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Caja generated by hbm2java
 */
public class Caja  implements java.io.Serializable {


     private int idcaja;
     private AreaCaja areaCaja;
     private Usuario usuario;
     private Date fechaApertura;
     private String horaApertura;
     private Date fechaCierre;
     private String horaCierre;
     private String estado;
     private BigDecimal saldoInicial;
     private BigDecimal saldoFinal;
     private BigDecimal saldoContabilizado;
     private BigDecimal descuadre;
     private String turno;
     private Set<Comprobante> comprobantes = new HashSet<Comprobante>(0);

    public Caja() {
        this.areaCaja = new AreaCaja();
        this.usuario = new Usuario();
    }

	
    public Caja(int idcaja, Date fechaApertura) {
        this.idcaja = idcaja;
        this.fechaApertura = fechaApertura;
    }
    public Caja(int idcaja, AreaCaja areaCaja,Usuario usuario, Date fechaApertura, String horaApertura, Date fechaCierre, String horaCierre, String estado, BigDecimal saldoInicial, BigDecimal saldoFinal, BigDecimal saldoContabilizado, BigDecimal descuadre, String turno, Set<Comprobante> comprobantes) {
       this.idcaja = idcaja;
       this.areaCaja = areaCaja;
       this.usuario = usuario;
       this.fechaApertura = fechaApertura;
       this.horaApertura = horaApertura;
       this.fechaCierre = fechaCierre;
       this.horaCierre = horaCierre;
       this.estado = estado;
       this.saldoInicial = saldoInicial;
       this.saldoFinal = saldoFinal;
       this.saldoContabilizado = saldoContabilizado;
       this.descuadre = descuadre;
       this.turno = turno;
       this.comprobantes = comprobantes;
    }
   
    public int getIdcaja() {
        return this.idcaja;
    }
    
    public void setIdcaja(int idcaja) {
        this.idcaja = idcaja;
    }
    public AreaCaja getAreaCaja() {
        return this.areaCaja;
    }
    
    public void setAreaCaja(AreaCaja areaCaja) {
        this.areaCaja = areaCaja;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaApertura() {
        return this.fechaApertura;
    }
    
    public void setFechaApertura(Date fechaApertura) {
        this.fechaApertura = fechaApertura;
    }
    public String getHoraApertura() {
        return this.horaApertura;
    }
    
    public void setHoraApertura(String horaApertura) {
        this.horaApertura = horaApertura;
    }
    public Date getFechaCierre() {
        return this.fechaCierre;
    }
    
    public void setFechaCierre(Date fechaCierre) {
        this.fechaCierre = fechaCierre;
    }
    public String getHoraCierre() {
        return this.horaCierre;
    }
    
    public void setHoraCierre(String horaCierre) {
        this.horaCierre = horaCierre;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public BigDecimal getSaldoInicial() {
        return this.saldoInicial;
    }
    
    public void setSaldoInicial(BigDecimal saldoInicial) {
        this.saldoInicial = saldoInicial;
    }
    public BigDecimal getSaldoFinal() {
        return this.saldoFinal;
    }
    
    public void setSaldoFinal(BigDecimal saldoFinal) {
        this.saldoFinal = saldoFinal;
    }
    public BigDecimal getSaldoContabilizado() {
        return this.saldoContabilizado;
    }
    
    public void setSaldoContabilizado(BigDecimal saldoContabilizado) {
        this.saldoContabilizado = saldoContabilizado;
    }
    public BigDecimal getDescuadre() {
        return this.descuadre;
    }
    
    public void setDescuadre(BigDecimal descuadre) {
        this.descuadre = descuadre;
    }
    public String getTurno() {
        return this.turno;
    }
    
    public void setTurno(String turno) {
        this.turno = turno;
    }
    public Set<Comprobante> getComprobantes() {
        return this.comprobantes;
    }
    
    public void setComprobantes(Set<Comprobante> comprobantes) {
        this.comprobantes = comprobantes;
    }




}


