package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cie10 generated by hbm2java
 */
public class Cie10  implements java.io.Serializable {


     private int idCie10;
     private String codigo;
     private String descripcion;

    public Cie10() {
    }

	
    public Cie10(int idCie10, String codigo) {
        this.idCie10 = idCie10;
        this.codigo = codigo;
    }
   
    public int getIdCie10() {
        return this.idCie10;
    }
    
    public void setIdCie10(int idCie10) {
        this.idCie10 = idCie10;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
}


