package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Cita generated by hbm2java
 */
public class Cita implements java.io.Serializable {

    private long idcita;
    private Persona persona;
    private long idUsuario;
    private Date fechaReg;
    private String horaInicio;
    private String horaFin;
    private Date fechaCita;
    private String estado;
    private String numeroCarta;
    private BigDecimal cobertura;
    private Date fechaVencimiento;
    private Beneficio beneficio;
    private int numero;

    public Cita() {
    }

    public long getIdcita() {
        return this.idcita;
    }

    public void setIdcita(long idcita) {
        this.idcita = idcita;
    }

    public Persona getPersona() {
        return this.persona;
    }

    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    public long getIdUsuario() {
        return this.idUsuario;
    }

    public void setIdUsuario(long idUsuario) {
        this.idUsuario = idUsuario;
    }

    public Date getFechaReg() {
        return this.fechaReg;
    }

    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }

    public String getHoraInicio() {
        return this.horaInicio;
    }

    public void setHoraInicio(String horaInicio) {
        this.horaInicio = horaInicio;
    }

    public String getHoraFin() {
        return this.horaFin;
    }

    public void setHoraFin(String horaFin) {
        this.horaFin = horaFin;
    }

    public Date getFechaCita() {
        return this.fechaCita;
    }

    public void setFechaCita(Date fechaCita) {
        this.fechaCita = fechaCita;
    }

    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public String getNumeroCarta() {
        return this.numeroCarta;
    }

    public void setNumeroCarta(String numeroCarta) {
        this.numeroCarta = numeroCarta;
    }

    public BigDecimal getCobertura() {
        return this.cobertura;
    }

    public void setCobertura(BigDecimal cobertura) {
        this.cobertura = cobertura;
    }

    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }

    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }


    public Beneficio getBeneficio() {
        return beneficio;
    }

    public void setBeneficio(Beneficio beneficio) {
        this.beneficio = beneficio;
    }

    public int getNumero() {
        return numero;
    }

    public void setNumero(int numero) {
        this.numero = numero;
    }

}
