package lissa.be;
// Generated 19/09/2018 03:22:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Comprobante generated by hbm2java
 */
public class Comprobante  implements java.io.Serializable {


     private long idcomprobante;
     private Atencion atencion;
     private Beneficio beneficio;
     private Caja caja;
     private TipoComprobante tipoComprobante;
     private TipoDocidentidad tipoDocCliente;
     private FondoSolidaridad fondoSolidaridad;
     private Organizacion organizacion;
     private Persona clientepersonanatural;
     private Date fechaComprobante;//Fecha de emision     
     private Date fechaReg;//Fecha de sistema para control interno
     private String horaReg;//Hora registro del comprobante
     private long numero;
     private BigDecimal subTotal;
     private BigDecimal montoIgv;
     private BigDecimal montoTotal;
     private String motivoAnulacion;
     private long idUsuario;
     private Integer numeroOperacion;
     private Integer grupoNumeracion;
     private String estado;
     private String serie;
     private String numeroCarta;
     //variables para la fact electronica
     private BigDecimal tipoCambio;
     private BigDecimal totalValorVentaOpGravadas;
     private BigDecimal totalValorVentaOpeInafectas;
     private BigDecimal totalValorVentaOpeExoneradas;
     private BigDecimal totalSumatoriaIgv;
     private BigDecimal totalSumatoriaIsc;
     private BigDecimal totalSumatoriaOtrosTributos;
     private BigDecimal totalSumatoriaOtrosCargos;
     private BigDecimal totalSumatoriaDescuentos;
     private BigDecimal totalImporteVenta;
     private String tipoMoneda;
     private BigDecimal totalOpeGratuitas;
     private Set<Pago> pagos = new HashSet<Pago>(0);
     private Set<ComprobanteDetalle> comprobanteDetalles = new HashSet<ComprobanteDetalle>(0);
     private String correo_cliente_temp;

    public Comprobante() {
    }

   
    public long getIdcomprobante() {
        return this.idcomprobante;
    }
    
    public void setIdcomprobante(long idcomprobante) {
        this.idcomprobante = idcomprobante;
    }
    public Atencion getAtencion() {
        return this.atencion;
    }
    
    public void setAtencion(Atencion atencion) {
        this.atencion = atencion;
    }
    public Beneficio getBeneficio() {
        return this.beneficio;
    }
    
    public void setBeneficio(Beneficio beneficio) {
        this.beneficio = beneficio;
    }
    public Caja getCaja() {
        return this.caja;
    }
    
    public void setCaja(Caja caja) {
        this.caja = caja;
    }
    public TipoComprobante getTipoComprobante() {
        return this.tipoComprobante;
    }
    
    public void setTipoComprobante(TipoComprobante tipoComprobante) {
        this.tipoComprobante = tipoComprobante;
    }
    public Date getFechaComprobante() {
        return this.fechaComprobante;
    }
    
    public void setFechaComprobante(Date fechaComprobante) {
        this.fechaComprobante = fechaComprobante;
    }

    public String getHoraReg() {
        return horaReg;
    }

    public void setHoraReg(String horaReg) {
        this.horaReg = horaReg;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public long getNumero() {
        return this.numero;
    }
    
    public void setNumero(long numero) {
        this.numero = numero;
    }
    public BigDecimal getSubTotal() {
        return this.subTotal;
    }
    
    public void setSubTotal(BigDecimal subTotal) {
        this.subTotal = subTotal;
    }
    public BigDecimal getMontoIgv() {
        return this.montoIgv;
    }
    
    public void setMontoIgv(BigDecimal montoIgv) {
        this.montoIgv = montoIgv;
    }
    public BigDecimal getMontoTotal() {
        return this.montoTotal;
    }
    
    public void setMontoTotal(BigDecimal montoTotal) {
        this.montoTotal = montoTotal;
    }
    public String getMotivoAnulacion() {
        return this.motivoAnulacion;
    }
    
    public void setMotivoAnulacion(String motivoAnulacion) {
        this.motivoAnulacion = motivoAnulacion;
    }
    public long getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(long idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Integer getNumeroOperacion() {
        return this.numeroOperacion;
    }
    
    public void setNumeroOperacion(Integer numeroOperacion) {
        this.numeroOperacion = numeroOperacion;
    }
    public Integer getGrupoNumeracion() {
        return this.grupoNumeracion;
    }
    
    public void setGrupoNumeracion(Integer grupoNumeracion) {
        this.grupoNumeracion = grupoNumeracion;
    }
  
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<Pago> getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set<Pago> pagos) {
        this.pagos = pagos;
    }
    public Set<ComprobanteDetalle> getComprobanteDetalles() {
        return this.comprobanteDetalles;
    }
    
    public void setComprobanteDetalles(Set<ComprobanteDetalle> comprobanteDetalles) {
        this.comprobanteDetalles = comprobanteDetalles;
    }

    public String getSerie() {
        return serie;
    }

    public void setSerie(String serie) {
        this.serie = serie;
    }

    public FondoSolidaridad getFondoSolidaridad() {
        return fondoSolidaridad;
    }

    public void setFondoSolidaridad(FondoSolidaridad fondoSolidaridad) {
        this.fondoSolidaridad = fondoSolidaridad;
    }

    public String getNumeroCarta() {
        return numeroCarta;
    }

    public void setNumeroCarta(String numeroCarta) {
        this.numeroCarta = numeroCarta;
    }

   

    public Persona getClientepersonanatural() {
        return clientepersonanatural;
    }

    public void setClientepersonanatural(Persona clientepersonanatural) {
        this.clientepersonanatural = clientepersonanatural;
    }
    public Organizacion getOrganizacion() {
        return organizacion;
    }

    public void setOrganizacion(Organizacion organizacion) {
        this.organizacion = organizacion;
    }

    public BigDecimal getTipoCambio() {
        return tipoCambio;
    }

    public void setTipoCambio(BigDecimal tipoCambio) {
        this.tipoCambio = tipoCambio;
    }

    public BigDecimal getTotalValorVentaOpGravadas() {
        return totalValorVentaOpGravadas;
    }

    public void setTotalValorVentaOpGravadas(BigDecimal totalValorVentaOpGravadas) {
        this.totalValorVentaOpGravadas = totalValorVentaOpGravadas;
    }

    public BigDecimal getTotalValorVentaOpeInafectas() {
        return totalValorVentaOpeInafectas;
    }

    public void setTotalValorVentaOpeInafectas(BigDecimal totalValorVentaOpeInafectas) {
        this.totalValorVentaOpeInafectas = totalValorVentaOpeInafectas;
    }

    public BigDecimal getTotalValorVentaOpeExoneradas() {
        return totalValorVentaOpeExoneradas;
    }

    public void setTotalValorVentaOpeExoneradas(BigDecimal totalValorVentaOpeExoneradas) {
        this.totalValorVentaOpeExoneradas = totalValorVentaOpeExoneradas;
    }

    public BigDecimal getTotalSumatoriaIgv() {
        return totalSumatoriaIgv;
    }

    public void setTotalSumatoriaIgv(BigDecimal totalSumatoriaIgv) {
        this.totalSumatoriaIgv = totalSumatoriaIgv;
    }

    public BigDecimal getTotalSumatoriaIsc() {
        return totalSumatoriaIsc;
    }

    public void setTotalSumatoriaIsc(BigDecimal totalSumatoriaIsc) {
        this.totalSumatoriaIsc = totalSumatoriaIsc;
    }

    public BigDecimal getTotalSumatoriaOtrosTributos() {
        return totalSumatoriaOtrosTributos;
    }

    public void setTotalSumatoriaOtrosTributos(BigDecimal totalSumatoriaOtrosTributos) {
        this.totalSumatoriaOtrosTributos = totalSumatoriaOtrosTributos;
    }

    public BigDecimal getTotalSumatoriaOtrosCargos() {
        return totalSumatoriaOtrosCargos;
    }

    public void setTotalSumatoriaOtrosCargos(BigDecimal totalSumatoriaOtrosCargos) {
        this.totalSumatoriaOtrosCargos = totalSumatoriaOtrosCargos;
    }

    public BigDecimal getTotalSumatoriaDescuentos() {
        return totalSumatoriaDescuentos;
    }

    public void setTotalSumatoriaDescuentos(BigDecimal totalSumatoriaDescuentos) {
        this.totalSumatoriaDescuentos = totalSumatoriaDescuentos;
    }

    public BigDecimal getTotalImporteVenta() {
        return totalImporteVenta;
    }

    public void setTotalImporteVenta(BigDecimal totalImporteVenta) {
        this.totalImporteVenta = totalImporteVenta;
    }

    public String getTipoMoneda() {
        return tipoMoneda;
    }

    public void setTipoMoneda(String tipoMoneda) {
        this.tipoMoneda = tipoMoneda;
    }

    public BigDecimal getTotalOpeGratuitas() {
        return totalOpeGratuitas;
    }

    public void setTotalOpeGratuitas(BigDecimal totalOpeGratuitas) {
        this.totalOpeGratuitas = totalOpeGratuitas;
    }

    public TipoDocidentidad getTipoDocCliente() {
        return tipoDocCliente;
    }

    public void setTipoDocCliente(TipoDocidentidad tipoDocCliente) {
        this.tipoDocCliente = tipoDocCliente;
    }

    public String getCorreo_cliente_temp() {
        return correo_cliente_temp;
    }

    public void setCorreo_cliente_temp(String correo_cliente_temp) {
        this.correo_cliente_temp = correo_cliente_temp;
    }

}


