package lissa.be;
// Generated 19/09/2018 03:22:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ComprobanteDetalle generated by hbm2java
 */
public class ComprobanteDetalle  implements java.io.Serializable {
     private long idcomprobantedetalle;
     private Comprobante comprobante;
     private Medico medicoByIdMedicoDeriva;
     private Medico medicoByIdMedicoAtiende;
     private ProcedimientoTarifario procedimientoTarifario;
     private BigDecimal montoProcedimiento;
     private String concepto;
     private Date fechaReg;
     private Date fechaAtencion;
     private BigDecimal montoAtencion;
     private BigDecimal montoDerivacion;
     private BigDecimal montoPagado;
     private BigDecimal importeAdicional;
     private int porcCubierto;
     private BigDecimal montoCubierto;
     private BigDecimal montoCubiertoSoles;
     private String observacion;
     private Medico medicoatiendereal;
     private String observacionTriaje;
     private String estado;
     
     private String unidadMedida;
     private BigDecimal cantidad;
     private long idTipoigv;
     private BigDecimal valorUnitarioItem;
     private BigDecimal precioUnitarioItem;
     private BigDecimal subTotal;
     private BigDecimal montoIgvItem;
     private BigDecimal montoTotal;
     
     private Set<MedicoDerivaAtiende> medicoDerivaAtiendes = new HashSet<MedicoDerivaAtiende>(0);

    public ComprobanteDetalle() {
    }

	
    public ComprobanteDetalle(long idcomprobantedetalle, Comprobante comprobante, Date fechaReg, int porcCubierto, BigDecimal montoCubierto) {
        this.idcomprobantedetalle = idcomprobantedetalle;
        this.comprobante = comprobante;
        this.fechaReg = fechaReg;
        this.porcCubierto = porcCubierto;
        this.montoCubierto = montoCubierto;
    }
  
   
    public long getIdcomprobantedetalle() {
        return this.idcomprobantedetalle;
    }
    
    public void setIdcomprobantedetalle(long idcomprobantedetalle) {
        this.idcomprobantedetalle = idcomprobantedetalle;
    }
    public Comprobante getComprobante() {
        return this.comprobante;
    }
    
    public void setComprobante(Comprobante comprobante) {
        this.comprobante = comprobante;
    }
    public Medico getMedicoByIdMedicoDeriva() {
        return this.medicoByIdMedicoDeriva;
    }
    
    public void setMedicoByIdMedicoDeriva(Medico medicoByIdMedicoDeriva) {
        this.medicoByIdMedicoDeriva = medicoByIdMedicoDeriva;
    }
    public Medico getMedicoByIdMedicoAtiende() {
        return this.medicoByIdMedicoAtiende;
    }
    
    public void setMedicoByIdMedicoAtiende(Medico medicoByIdMedicoAtiende) {
        this.medicoByIdMedicoAtiende = medicoByIdMedicoAtiende;
    }
    public ProcedimientoTarifario getProcedimientoTarifario() {
        return this.procedimientoTarifario;
    }
    
    public void setProcedimientoTarifario(ProcedimientoTarifario procedimiento) {
        this.procedimientoTarifario = procedimiento;
    }
    public BigDecimal getMontoProcedimiento() {
        return this.montoProcedimiento;
    }
    
    public void setMontoProcedimiento(BigDecimal montoProcedimiento) {
        this.montoProcedimiento = montoProcedimiento;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public BigDecimal getMontoAtencion() {
        return this.montoAtencion;
    }
    
    public void setMontoAtencion(BigDecimal montoAtencion) {
        this.montoAtencion = montoAtencion;
    }
    public BigDecimal getMontoDerivacion() {
        return this.montoDerivacion;
    }
    
    public void setMontoDerivacion(BigDecimal montoDerivacion) {
        this.montoDerivacion = montoDerivacion;
    }
    public BigDecimal getMontoPagado() {
        return this.montoPagado;
    }
    
    public void setMontoPagado(BigDecimal montoPagado) {
        this.montoPagado = montoPagado;
    }
    public BigDecimal getImporteAdicional() {
        return this.importeAdicional;
    }
    
    public void setImporteAdicional(BigDecimal importeAdicional) {
        this.importeAdicional = importeAdicional;
    }
    public int getPorcCubierto() {
        return this.porcCubierto;
    }
    
    public void setPorcCubierto(int porcCubierto) {
        this.porcCubierto = porcCubierto;
    }
    public BigDecimal getMontoCubierto() {
        return this.montoCubierto;
    }
    
    public void setMontoCubierto(BigDecimal montoCubierto) {
        this.montoCubierto = montoCubierto;
    }
    public BigDecimal getMontoCubiertoSoles() {
        return this.montoCubiertoSoles;
    }
    
    public void setMontoCubiertoSoles(BigDecimal montoCubiertoSoles) {
        this.montoCubiertoSoles = montoCubiertoSoles;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Set<MedicoDerivaAtiende> getMedicoDerivaAtiendes() {
        return this.medicoDerivaAtiendes;
    }
    
    public void setMedicoDerivaAtiendes(Set<MedicoDerivaAtiende> medicoDerivaAtiendes) {
        this.medicoDerivaAtiendes = medicoDerivaAtiendes;
    }

    public Medico getMedicoatiendereal() {
        return medicoatiendereal;
    }

    public void setMedicoatiendereal(Medico medicoatiendereal) {
        this.medicoatiendereal = medicoatiendereal;
    }

    public String getObservacionTriaje() {
        return observacionTriaje;
    }

    public void setObservacionTriaje(String observacionTriaje) {
        this.observacionTriaje = observacionTriaje;
    }

    public Date getFechaAtencion() {
        return fechaAtencion;
    }

    public void setFechaAtencion(Date fechaAtencion) {
        this.fechaAtencion = fechaAtencion;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public String getUnidadMedida() {
        return unidadMedida;
    }

    public void setUnidadMedida(String unidadMedida) {
        this.unidadMedida = unidadMedida;
    }

    public BigDecimal getCantidad() {
        return cantidad;
    }

    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }

    public long getIdTipoigv() {
        return idTipoigv;
    }

    public void setIdTipoigv(long idTipoigv) {
        this.idTipoigv = idTipoigv;
    }

    public BigDecimal getValorUnitarioItem() {
        return valorUnitarioItem;
    }

    public void setValorUnitarioItem(BigDecimal valorUnitarioItem) {
        this.valorUnitarioItem = valorUnitarioItem;
    }

    public BigDecimal getPrecioUnitarioItem() {
        return precioUnitarioItem;
    }

    public void setPrecioUnitarioItem(BigDecimal precioUnitarioItem) {
        this.precioUnitarioItem = precioUnitarioItem;
    }

    public BigDecimal getSubTotal() {
        return subTotal;
    }

    public void setSubTotal(BigDecimal subTotal) {
        this.subTotal = subTotal;
    }

    public BigDecimal getMontoIgvItem() {
        return montoIgvItem;
    }

    public void setMontoIgvItem(BigDecimal montoIgvItem) {
        this.montoIgvItem = montoIgvItem;
    }

    public BigDecimal getMontoTotal() {
        return montoTotal;
    }

    public void setMontoTotal(BigDecimal montoTotal) {
        this.montoTotal = montoTotal;
    }

}


