package lissa.be;
// Generated 14/06/2017 04:06:49 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Cuentaxcobrar generated by hbm2java
 */
public class Cuentaxcobrar implements java.io.Serializable {

    private long idcuentaxcobrar;
    private Venta venta;
    private Usuario usuario;
    private Beneficio beneficio;
    private FondoSolidaridad fondoSolidaridad;
    private String estado;
    private Date fechaPago;
    private BigDecimal montoPagado;    
    private BigDecimal total;
    private double porcDesc;
    private BigDecimal montoDesc;
    private double porcCopago;
    private BigDecimal montoCopago;
    private BigDecimal cuentaXCobrar;
    private BigDecimal montoPagofps;

    public Cuentaxcobrar() {
    }



    public long getIdcuentaxcobrar() {
        return this.idcuentaxcobrar;
    }

    public void setIdcuentaxcobrar(long idcuentaxcobrar) {
        this.idcuentaxcobrar = idcuentaxcobrar;
    }

    public Venta getVenta() {
        return this.venta;
    }

    public void setVenta(Venta venta) {
        this.venta = venta;
    }


    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public Date getFechaPago() {
        return this.fechaPago;
    }

    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }

    public BigDecimal getMontoPagado() {
        return this.montoPagado;
    }

    public void setMontoPagado(BigDecimal montoPagado) {
        this.montoPagado = montoPagado;
    }
    public BigDecimal getTotal() {
        return this.total;
    }

    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    public double getPorcDesc() {
        return this.porcDesc;
    }

    public void setPorcDesc(double porcDesc) {
        this.porcDesc = porcDesc;
    }

    public BigDecimal getMontoDesc() {
        return this.montoDesc;
    }

    public void setMontoDesc(BigDecimal montoDesc) {
        this.montoDesc = montoDesc;
    }

    public double getPorcCopago() {
        return this.porcCopago;
    }

    public void setPorcCopago(double porcCopago) {
        this.porcCopago = porcCopago;
    }

    public BigDecimal getMontoCopago() {
        return this.montoCopago;
    }

    public void setMontoCopago(BigDecimal montoCopago) {
        this.montoCopago = montoCopago;
    }

    public BigDecimal getCuentaXCobrar() {
        return this.cuentaXCobrar;
    }

    public void setCuentaXCobrar(BigDecimal cuentaXCobrar) {
        this.cuentaXCobrar = cuentaXCobrar;
    }

    public BigDecimal getMontoPagofps() {
        return this.montoPagofps;
    }

    public void setMontoPagofps(BigDecimal montoPagofps) {
        this.montoPagofps = montoPagofps;
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public Beneficio getBeneficio() {
        return beneficio;
    }

    public void setBeneficio(Beneficio beneficio) {
        this.beneficio = beneficio;
    }

    public FondoSolidaridad getFondoSolidaridad() {
        return fondoSolidaridad;
    }

    public void setFondoSolidaridad(FondoSolidaridad fondoSolidaridad) {
        this.fondoSolidaridad = fondoSolidaridad;
    }
}
