package lissa.be;
// Generated 19-oct-2016 12:42:31 by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * DetalleVenta generated by hbm2java
 */
public class DetalleVenta implements java.io.Serializable {

    private long iddetalleventa;
    private Producto producto;
    private Venta venta;
    private BigDecimal precioVenta;
    private BigDecimal cantidadVenta;
    private String lote;
    private Long idAlmacenproducto;
    //variables para almacenar precio de venta temporales
    private BigDecimal pvMin;
    private BigDecimal pvMax;
    private BigDecimal pvSugerido;
    private String unidadMedida;
    private long idTipoigv;
    private BigDecimal valorUnitarioItem;
    private BigDecimal precioUnitarioItem;
    private BigDecimal subTotal;
    private BigDecimal montoIgvItem;
    private BigDecimal montoTotal;

    public DetalleVenta() {
    }
    
    public long getIddetalleventa() {
        return this.iddetalleventa;
    }

    public void setIddetalleventa(long iddetalleventa) {
        this.iddetalleventa = iddetalleventa;
    }

    public Producto getProducto() {
        return this.producto;
    }

    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    public Venta getVenta() {
        return this.venta;
    }

    public void setVenta(Venta venta) {
        this.venta = venta;
    }

    public BigDecimal getPrecioVenta() {
        return this.precioVenta;
    }

    public void setPrecioVenta(BigDecimal precioVenta) {
        this.precioVenta = precioVenta;
    }

    public String getLote() {
        return lote;
    }

    public void setLote(String lote) {
        this.lote = lote;
    }

    public Long getIdAlmacenproducto() {
        return idAlmacenproducto;
    }

    public void setIdAlmacenproducto(Long idAlmacenproducto) {
        this.idAlmacenproducto = idAlmacenproducto;
    }

    public BigDecimal getPvMin() {
        return pvMin;
    }

    public void setPvMin(BigDecimal pvMin) {
        this.pvMin = pvMin;
    }

    public BigDecimal getPvMax() {
        return pvMax;
    }

    public void setPvMax(BigDecimal pvMax) {
        this.pvMax = pvMax;
    }

    public BigDecimal getPvSugerido() {
        return pvSugerido;
    }

    public void setPvSugerido(BigDecimal pvSugerido) {
        this.pvSugerido = pvSugerido;
    }

    public String getUnidadMedida() {
        return unidadMedida;
    }

    public void setUnidadMedida(String unidadMedida) {
        this.unidadMedida = unidadMedida;
    }

    public long getIdTipoigv() {
        return idTipoigv;
    }

    public void setIdTipoigv(long idTipoigv) {
        this.idTipoigv = idTipoigv;
    }

    public BigDecimal getValorUnitarioItem() {
        return valorUnitarioItem;
    }

    public void setValorUnitarioItem(BigDecimal valorUnitarioItem) {
        this.valorUnitarioItem = valorUnitarioItem;
    }

    public BigDecimal getPrecioUnitarioItem() {
        return precioUnitarioItem;
    }

    public void setPrecioUnitarioItem(BigDecimal precioUnitarioItem) {
        this.precioUnitarioItem = precioUnitarioItem;
    }

    public BigDecimal getSubTotal() {
        return subTotal;
    }

    public void setSubTotal(BigDecimal subTotal) {
        this.subTotal = subTotal;
    }

    public BigDecimal getMontoIgvItem() {
        return montoIgvItem;
    }

    public void setMontoIgvItem(BigDecimal montoIgvItem) {
        this.montoIgvItem = montoIgvItem;
    }

    public BigDecimal getMontoTotal() {
        return montoTotal;
    }

    public void setMontoTotal(BigDecimal montoTotal) {
        this.montoTotal = montoTotal;
    }

    public BigDecimal getCantidadVenta() {
        return cantidadVenta;
    }

    public void setCantidadVenta(BigDecimal cantidadVenta) {
        this.cantidadVenta = cantidadVenta;
    }

}
