package lissa.be;
// Generated 13/10/2018 06:05:34 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Egreso generated by hbm2java
 */
public class Egreso  implements java.io.Serializable {
     private long idegreso;
     private long numero;
     private Date fecha;
     private String motivo;
     private String motivoOtros;
     private Long idPersona;
     private String nroComprobante;
     private String tipoComprobante;
     private String observacion;
     private long idUsuario;
     private Long idCajaafecto;
     private int estado;
     private BigDecimal monto;
     private Set<EgresoDetalle> egresoDetalles = new HashSet<EgresoDetalle>(0);

    public Egreso() {
    }

	
    public Egreso(int idegreso, long numero, Date fecha, String motivo, long idUsuario, int estado) {
        this.idegreso = idegreso;
        this.numero = numero;
        this.fecha = fecha;
        this.motivo = motivo;
        this.idUsuario = idUsuario;
        this.estado = estado;
    }
    public Egreso(long idegreso, long numero, Date fecha, String motivo, String motivoOtros, Long idPersona, String nroComprobante, String tipoComprobante, String observacion, long idUsuario, Long idCajaafecto, int estado, BigDecimal monto, Set<EgresoDetalle> egresoDetalles) {
       this.idegreso = idegreso;
       this.numero = numero;
       this.fecha = fecha;
       this.motivo = motivo;
       this.motivoOtros = motivoOtros;
       this.idPersona = idPersona;
       this.nroComprobante = nroComprobante;
       this.tipoComprobante = tipoComprobante;
       this.observacion = observacion;
       this.idUsuario = idUsuario;
       this.idCajaafecto = idCajaafecto;
       this.estado = estado;
       this.monto = monto;
       this.egresoDetalles = egresoDetalles;
    }
   
    public long getIdegreso() {
        return this.idegreso;
    }
    
    public void setIdegreso(long idegreso) {
        this.idegreso = idegreso;
    }
    public long getNumero() {
        return this.numero;
    }
    
    public void setNumero(long numero) {
        this.numero = numero;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }
    public String getMotivoOtros() {
        return this.motivoOtros;
    }
    
    public void setMotivoOtros(String motivoOtros) {
        this.motivoOtros = motivoOtros;
    }
    public Long getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Long idPersona) {
        this.idPersona = idPersona;
    }
    public String getNroComprobante() {
        return this.nroComprobante;
    }
    
    public void setNroComprobante(String nroComprobante) {
        this.nroComprobante = nroComprobante;
    }
    public String getTipoComprobante() {
        return this.tipoComprobante;
    }
    
    public void setTipoComprobante(String tipoComprobante) {
        this.tipoComprobante = tipoComprobante;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public long getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(long idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Long getIdCajaafecto() {
        return this.idCajaafecto;
    }
    
    public void setIdCajaafecto(Long idCajaafecto) {
        this.idCajaafecto = idCajaafecto;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    public Set<EgresoDetalle> getEgresoDetalles() {
        return this.egresoDetalles;
    }
    
    public void setEgresoDetalles(Set<EgresoDetalle> egresoDetalles) {
        this.egresoDetalles = egresoDetalles;
    }




}


