package lissa.be;
// Generated 13/10/2018 06:05:34 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * EgresoDetalle generated by hbm2java
 */
public class EgresoDetalle  implements java.io.Serializable {


     private long idegresodetalle;
     private Egreso egreso;
     private MedicoDerivaAtiende medicoDerivaAtiende;
     private String descripcion;
     private int cantidad;
     private BigDecimal monto;

    public EgresoDetalle() {
    }

	
    public EgresoDetalle(int idegresodetalle, Egreso egreso, int cantidad, BigDecimal monto) {
        this.idegresodetalle = idegresodetalle;
        this.egreso = egreso;
        this.cantidad = cantidad;
        this.monto = monto;
    }
    public EgresoDetalle(int idegresodetalle, Egreso egreso, MedicoDerivaAtiende medicoDerivaAtiende, String descripcion, int cantidad, BigDecimal monto) {
       this.idegresodetalle = idegresodetalle;
       this.egreso = egreso;
       this.medicoDerivaAtiende = medicoDerivaAtiende;
       this.descripcion = descripcion;
       this.cantidad = cantidad;
       this.monto = monto;
    }
   
    public long getIdegresodetalle() {
        return this.idegresodetalle;
    }
    
    public void setIdegresodetalle(long idegresodetalle) {
        this.idegresodetalle = idegresodetalle;
    }
    public Egreso getEgreso() {
        return this.egreso;
    }
    
    public void setEgreso(Egreso egreso) {
        this.egreso = egreso;
    }
    public MedicoDerivaAtiende getMedicoDerivaAtiende() {
        return this.medicoDerivaAtiende;
    }
    
    public void setMedicoDerivaAtiende(MedicoDerivaAtiende medicoDerivaAtiende) {
        this.medicoDerivaAtiende = medicoDerivaAtiende;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }




}


