package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Especialidad generated by hbm2java
 */
public class Especialidad implements java.io.Serializable {

    private int idEspecialidad;
    private String denominacion;
    private Boolean estado;
    private Set<MedicoEspecialidad> medicoEspecialidads = new HashSet<MedicoEspecialidad>(0);
    public static final int DEFECTO = -1, DATO = 3;
    private int op = -1;

    public Especialidad() {
    }

    public Especialidad(int idEspecialidad) {
        this.idEspecialidad = idEspecialidad;
    }

    public Especialidad(int idEspecialidad, String denominacion, Boolean estado, Set<MedicoEspecialidad> medicoEspecialidads) {
        this.idEspecialidad = idEspecialidad;
        this.denominacion = denominacion;
        this.estado = estado;
        this.medicoEspecialidads = medicoEspecialidads;
    }

    public int getIdEspecialidad() {
        return this.idEspecialidad;
    }

    public void setIdEspecialidad(int idEspecialidad) {
        this.idEspecialidad = idEspecialidad;
    }

    public String getDenominacion() {
        return this.denominacion;
    }

    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }

    public Boolean getEstado() {
        return this.estado;
    }

    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    public Set<MedicoEspecialidad> getMedicoEspecialidads() {
        return this.medicoEspecialidads;
    }

    public void setMedicoEspecialidads(Set<MedicoEspecialidad> medicoEspecialidads) {
        this.medicoEspecialidads = medicoEspecialidads;
    }

    public int getOp() {
        return op;
    }

    public void setOp(int op) {
        this.op = op;
    }
    
    @Override
    public String toString() {
        switch (op) {
            case DATO:
                return getDenominacion();
            default:
                return "<SELECCIONE>";
        }
    }

}
