package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * EstadoCivil generated by hbm2java
 */
public class EstadoCivil implements java.io.Serializable {

    private long idestadocivil;
    private String estadoCivil;
    private Boolean estado;
    private Set<Persona> personas = new HashSet<Persona>(0);
    public static final int DEFECTO = -1, DATO = 3;
    private int op = -1;

    public EstadoCivil() {
    }

   

    public int getOp() {
        return op;
    }

    public void setOp(int op) {
        this.op = op;
    }

    @Override
    public String toString() {
        switch (op) {
            case DATO:
                return getEstadoCivil();
            default:
                return "<SELECCIONE>";
        }
    }

    public long getIdestadocivil() {
        return idestadocivil;
    }

    public void setIdestadocivil(long idestadocivil) {
        this.idestadocivil = idestadocivil;
    }

    public String getEstadoCivil() {
        return estadoCivil;
    }

    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }

    public Boolean getEstado() {
        return estado;
    }

    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    public Set<Persona> getPersonas() {
        return personas;
    }

    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }

}
