package lissa.be;
// Generated 19/04/2018 04:37:19 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * FarComprobante generated by hbm2java
 */
public class FarComprobante implements java.io.Serializable {

    private long idfarcomprobante;
    private String comprobante;
    private String tipoComprobante;
    private boolean estado;
    private String codigoSunat;
    private int grupoNumeracion;
    private Set<Venta> ventas = new HashSet<Venta>(0);
    private Set<Compra> compras = new HashSet<Compra>(0);
    public static final int DEFECTO = 1, DATO = 3;
    private int op = -1;
    public static final String VENTA = "VENTA", COMPRA = "COMPRA", DISTRIBUCION = "DISTRIBUCION";

    public FarComprobante() {
    }

    public long getIdfarcomprobante() {
        return this.idfarcomprobante;
    }

    public void setIdfarcomprobante(long idfarcomprobante) {
        this.idfarcomprobante = idfarcomprobante;
    }

    public String getComprobante() {
        return this.comprobante;
    }

    public void setComprobante(String comprobante) {
        this.comprobante = comprobante;
    }

    public String getTipoComprobante() {
        return this.tipoComprobante;
    }

    public void setTipoComprobante(String tipoComprobante) {
        this.tipoComprobante = tipoComprobante;
    }

    public boolean isEstado() {
        return this.estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    public Set<Venta> getVentas() {
        return this.ventas;
    }

    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }

    public Set<Compra> getCompras() {
        return this.compras;
    }

    public void setCompras(Set<Compra> compras) {
        this.compras = compras;
    }

    public int getOp() {
        return op;
    }

    public void setOp(int op) {
        this.op = op;
    }

    @Override
    public String toString() {
        switch(getOp()){
            case DATO : return getComprobante();
            default: return "<SELECCIONE>";
        }
    }

    public String getCodigoSunat() {
        return codigoSunat;
    }

    public void setCodigoSunat(String codigoSunat) {
        this.codigoSunat = codigoSunat;
    }

    public int getGrupoNumeracion() {
        return grupoNumeracion;
    }

    public void setGrupoNumeracion(int grupoNumeracion) {
        this.grupoNumeracion = grupoNumeracion;
    }
    
    

}
