package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FondoSolidaridad generated by hbm2java
 */
public class FondoSolidaridad  implements java.io.Serializable {


     private long idFondosolidaridad;
     private Persona persona;
     private Date fechaReg;
     private Boolean estado;
     private BigDecimal importe;
     private Set<ServiciosFondoSolidaridad> serviciosFondoSolidaridads = new HashSet<ServiciosFondoSolidaridad>(0);
     private Set<HistorialAtencionFps> historialAtencionFpses = new HashSet<HistorialAtencionFps>(0);

    public FondoSolidaridad() {
    }

	
    public FondoSolidaridad(long idFondoSolidaridad) {
        this.idFondosolidaridad = idFondoSolidaridad;
    }
    
   
    public long getIdFondosolidaridad() {
        return this.idFondosolidaridad;
    }
    
    public void setIdFondosolidaridad(long idFondosolidaridad) {
        this.idFondosolidaridad = idFondosolidaridad;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public BigDecimal getImporte() {
        return this.importe;
    }
    
    public void setImporte(BigDecimal importe) {
        this.importe = importe;
    }

    public Set<ServiciosFondoSolidaridad> getServiciosFondoSolidaridads() {
        return serviciosFondoSolidaridads;
    }

    public void setServiciosFondoSolidaridads(Set<ServiciosFondoSolidaridad> serviciosFondoSolidaridads) {
        this.serviciosFondoSolidaridads = serviciosFondoSolidaridads;
    }

    public Set<HistorialAtencionFps> getHistorialAtencionFpses() {
        return historialAtencionFpses;
    }

    public void setHistorialAtencionFpses(Set<HistorialAtencionFps> historialAtencionFpses) {
        this.historialAtencionFpses = historialAtencionFpses;
    }
}


