package lissa.be;
// Generated 07/06/2018 05:59:42 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * FondoPrevisionTemp generated by hbm2java
 */
public class FondoPrevisionTemp  implements java.io.Serializable {


     private int idFondoprevtemp;
     private String nombres;
     private String apePaterno;
     private String apeMaterno;
     private String numDoc;
     private String codSocio;
     private Date fechaUltimoPago;
     private BigDecimal importePago;

    public FondoPrevisionTemp() {
    }

	
    public FondoPrevisionTemp(int idFondoprevtemp) {
        this.idFondoprevtemp = idFondoprevtemp;
    }
    public FondoPrevisionTemp(int idFondoprevtemp, String nombres, String apePaterno, String apeMaterno, String numDoc, String codSocio, Date fechaUltimoPago, BigDecimal importePago) {
       this.idFondoprevtemp = idFondoprevtemp;
       this.nombres = nombres;
       this.apePaterno = apePaterno;
       this.apeMaterno = apeMaterno;
       this.numDoc = numDoc;
       this.codSocio = codSocio;
       this.fechaUltimoPago = fechaUltimoPago;
       this.importePago = importePago;
    }
   
    public int getIdFondoprevtemp() {
        return this.idFondoprevtemp;
    }
    
    public void setIdFondoprevtemp(int idFondoprevtemp) {
        this.idFondoprevtemp = idFondoprevtemp;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApePaterno() {
        return this.apePaterno;
    }
    
    public void setApePaterno(String apePaterno) {
        this.apePaterno = apePaterno;
    }
    public String getApeMaterno() {
        return this.apeMaterno;
    }
    
    public void setApeMaterno(String apeMaterno) {
        this.apeMaterno = apeMaterno;
    }
    public String getNumDoc() {
        return this.numDoc;
    }
    
    public void setNumDoc(String numDoc) {
        this.numDoc = numDoc;
    }
    public String getCodSocio() {
        return this.codSocio;
    }
    
    public void setCodSocio(String codSocio) {
        this.codSocio = codSocio;
    }
    public Date getFechaUltimoPago() {
        return this.fechaUltimoPago;
    }
    
    public void setFechaUltimoPago(Date fechaUltimoPago) {
        this.fechaUltimoPago = fechaUltimoPago;
    }
    public BigDecimal getImportePago() {
        return this.importePago;
    }
    
    public void setImportePago(BigDecimal importePago) {
        this.importePago = importePago;
    }




}


