package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FormaPago generated by hbm2java
 */
public class FormaPago  implements java.io.Serializable {


     private int idformapago;
     private String nombre;
     private String observaciones;
     private Boolean estado;
     private Set<Pago> pagos = new HashSet<Pago>(0);

    public FormaPago() {
    }

	
    public FormaPago(int idformapago) {
        this.idformapago = idformapago;
    }
    public FormaPago(int idformapago, String nombre, String observaciones, Boolean estado, Set<Pago> pagos) {
       this.idformapago = idformapago;
       this.nombre = nombre;
       this.observaciones = observaciones;
       this.estado = estado;
       this.pagos = pagos;
    }
   
    public int getIdformapago() {
        return this.idformapago;
    }
    
    public void setIdformapago(int idformapago) {
        this.idformapago = idformapago;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set<Pago> getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set<Pago> pagos) {
        this.pagos = pagos;
    }




}


