package lissa.be;
// Generated 25-ago-2016 12:39:40 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * FormaFarmaceutica generated by hbm2java
 */
public class FormaFarmaceutica implements java.io.Serializable {

    private long idformafarmaceutica;
    private String denominacion;
    private boolean estado;
    private Set<Producto> productos = new HashSet<Producto>(0);

    private int op = -1;
    public static final int DEFECTO = -1, DATO = 3;

    public FormaFarmaceutica() {
    }

    public long getIdformafarmaceutica() {
        return this.idformafarmaceutica;
    }

    public void setIdformafarmaceutica(long idformafarmaceutica) {
        this.idformafarmaceutica = idformafarmaceutica;
    }

    public String getDenominacion() {
        return this.denominacion;
    }

    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }

    public boolean isEstado() {
        return this.estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    public Set<Producto> getProductos() {
        return this.productos;
    }

    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }

    public int getOp() {
        return op;
    }

    public void setOp(int op) {
        this.op = op;
    }
    
    @Override
    public String toString() {
        switch (getOp()) {
            case DATO:
                return getDenominacion();
            default:
                return "<SELECCIONE>";
        }
    }

}
