package lissa.be;
// Generated 15/03/2017 09:10:09 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MedicoDerivaAtiende generated by hbm2java
 */
public class MedicoDerivaAtiende  implements java.io.Serializable {
     private int idmedicoderivaatiende;
     private ComprobanteDetalle comprobanteDetalle;
     private Medico medico;
     private BigDecimal monto;
     private String estadoPago;
     private String motivo;
     private Integer idCajaafecto;
     private Date fechaReg;
     private Date fechaPago;
     private Usuario usuarioreg;
     private Usuario usuariopago;
     //
     private boolean seleccionado; 
     private Set<EgresoDetalle> egresoDetalles = new HashSet<EgresoDetalle>(0);

    public MedicoDerivaAtiende() {
    }

    public MedicoDerivaAtiende(int idmedicoderivaatiende, ComprobanteDetalle itemsComprobante, Medico medico, BigDecimal monto, String estadoPago, String tipoMedico) {
       this.idmedicoderivaatiende = idmedicoderivaatiende;
       this.comprobanteDetalle = itemsComprobante;
       this.medico = medico;
       this.monto = monto;
       this.estadoPago = estadoPago;
       this.motivo = tipoMedico;
    }
   
    public int getIdmedicoderivaatiende() {
        return this.idmedicoderivaatiende;
    }
    
    public void setIdmedicoderivaatiende(int idmedicoderivaatiende) {
        this.idmedicoderivaatiende = idmedicoderivaatiende;
    }
    public ComprobanteDetalle getComprobanteDetalle() {
        return this.comprobanteDetalle;
    }
    
    public void setComprobanteDetalle(ComprobanteDetalle comprobanteDetalle) {
        this.comprobanteDetalle = comprobanteDetalle;
    }
    public Medico getMedico() {
        return this.medico;
    }
    
    public void setMedico(Medico medico) {
        this.medico = medico;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    public String getEstadoPago() {
        return this.estadoPago;
    }
    
    public void setEstadoPago(String estadoPago) {
        this.estadoPago = estadoPago;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }

    public Integer getIdCajaafecto() {
        return idCajaafecto;
    }

    public void setIdCajaafecto(Integer idCajaafecto) {
        this.idCajaafecto = idCajaafecto;
    }

    public Date getFechaReg() {
        return fechaReg;
    }

    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }

    public Date getFechaPago() {
        return fechaPago;
    }

    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }

    public boolean isSeleccionado() {
        return seleccionado;
    }

    public void setSeleccionado(boolean seleccionado) {
        this.seleccionado = seleccionado;
    }

    public Set<EgresoDetalle> getEgresoDetalles() {
        return egresoDetalles;
    }

    public void setEgresoDetalles(Set<EgresoDetalle> egresoDetalles) {
        this.egresoDetalles = egresoDetalles;
    }

    public Usuario getUsuarioreg() {
        return usuarioreg;
    }

    public void setUsuarioreg(Usuario usuarioreg) {
        this.usuarioreg = usuarioreg;
    }

    public Usuario getUsuariopago() {
        return usuariopago;
    }

    public void setUsuariopago(Usuario usuariopago) {
        this.usuariopago = usuariopago;
    }




}


