package lissa.be;
// Generated 27/12/2018 04:24:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Organizacion generated by hbm2java
 */
public class Organizacion  implements java.io.Serializable {


     private long idorganizacion;
     private String razonSocial;
     private String ruc;
     private String domicilioFiscal;
     private byte[] logo;
     private Set<Comprobante> comprobantes = new HashSet<Comprobante>(0);

    public Organizacion() {
    }

	
    public Organizacion(long idorganizacion, String razonSocial, String ruc, String domicilioFiscal) {
        this.idorganizacion = idorganizacion;
        this.razonSocial = razonSocial;
        this.ruc = ruc;
        this.domicilioFiscal = domicilioFiscal;
    }
    public Organizacion(long idorganizacion, String razonSocial, String ruc, String domicilioFiscal, byte[] logo, Set<Comprobante> comprobantes) {
       this.idorganizacion = idorganizacion;
       this.razonSocial = razonSocial;
       this.ruc = ruc;
       this.domicilioFiscal = domicilioFiscal;
       this.logo = logo;
       this.comprobantes = comprobantes;
    }
   
    public long getIdorganizacion() {
        return this.idorganizacion;
    }
    
    public void setIdorganizacion(long idorganizacion) {
        this.idorganizacion = idorganizacion;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    public String getDomicilioFiscal() {
        return this.domicilioFiscal;
    }
    
    public void setDomicilioFiscal(String domicilioFiscal) {
        this.domicilioFiscal = domicilioFiscal;
    }
    public byte[] getLogo() {
        return this.logo;
    }
    
    public void setLogo(byte[] logo) {
        this.logo = logo;
    }
    public Set<Comprobante> getComprobantes() {
        return this.comprobantes;
    }
    
    public void setComprobantes(Set<Comprobante> comprobantes) {
        this.comprobantes = comprobantes;
    }




}


