package lissa.be;
// Generated 14/06/2017 04:06:49 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * PaqueteFondoSolidaridad generated by hbm2java
 */
public class PaqueteFondoSolidaridad implements java.io.Serializable {

    private int idpaquetefs;
    private String paquete;
    private String estado;
    private Set<PaqueteFondoDetalle> paqueteFondoDetalles = new HashSet<PaqueteFondoDetalle>(0);
    private Set<ServiciosFondoSolidaridad> serviciosFondoSolidaridads = new HashSet<ServiciosFondoSolidaridad>(0);
    public static final int DEFECTO = -1, DATO = 3;
    private int op = -1;

    public PaqueteFondoSolidaridad() {
    }

    public PaqueteFondoSolidaridad(int idpaquetefs, String paquete, String estado) {
        this.idpaquetefs = idpaquetefs;
        this.paquete = paquete;
        this.estado = estado;
    }

    public PaqueteFondoSolidaridad(int idpaquetefs, String paquete, String estado, Set<PaqueteFondoDetalle> paqueteFondoDetalles, Set<ServiciosFondoSolidaridad> serviciosFondoSolidaridads) {
        this.idpaquetefs = idpaquetefs;
        this.paquete = paquete;
        this.estado = estado;
        this.paqueteFondoDetalles = paqueteFondoDetalles;
        this.serviciosFondoSolidaridads = serviciosFondoSolidaridads;
    }

    public int getIdpaquetefs() {
        return this.idpaquetefs;
    }

    public void setIdpaquetefs(int idpaquetefs) {
        this.idpaquetefs = idpaquetefs;
    }

    public String getPaquete() {
        return this.paquete;
    }

    public void setPaquete(String paquete) {
        this.paquete = paquete;
    }

    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public Set<PaqueteFondoDetalle> getPaqueteFondoDetalles() {
        return this.paqueteFondoDetalles;
    }

    public void setPaqueteFondoDetalles(Set<PaqueteFondoDetalle> paqueteFondoDetalles) {
        this.paqueteFondoDetalles = paqueteFondoDetalles;
    }

    public Set<ServiciosFondoSolidaridad> getServiciosFondoSolidaridads() {
        return this.serviciosFondoSolidaridads;
    }

    public void setServiciosFondoSolidaridads(Set<ServiciosFondoSolidaridad> serviciosFondoSolidaridads) {
        this.serviciosFondoSolidaridads = serviciosFondoSolidaridads;
    }

    public int getOp() {
        return op;
    }

    public void setOp(int op) {
        this.op = op;
    }
    
    @Override
    public String toString() {
        switch (op) {
            case DATO:
                return getPaquete();
            default:
                return "<Seleccione>";
        }
    }

}
