package lissa.be;
// Generated 01/10/2018 12:21:27 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Permiso generated by hbm2java
 */
public class Permiso  implements java.io.Serializable {


     private int idpermiso;
     private int codigo;
     private String permiso;
     private String descripcion;
     private Set<UsuarioPermiso> usuarioPermisos = new HashSet<UsuarioPermiso>(0);

    public Permiso() {
    }

	
    public Permiso(int idpermiso, int codigo, String permiso, String descripcion) {
        this.idpermiso = idpermiso;
        this.codigo = codigo;
        this.permiso = permiso;
        this.descripcion = descripcion;
    }
    public Permiso(int idpermiso, int codigo, String permiso, String descripcion, Set<UsuarioPermiso> usuarioPermisos) {
       this.idpermiso = idpermiso;
       this.codigo = codigo;
       this.permiso = permiso;
       this.descripcion = descripcion;
       this.usuarioPermisos = usuarioPermisos;
    }
   
    public int getIdpermiso() {
        return this.idpermiso;
    }
    
    public void setIdpermiso(int idpermiso) {
        this.idpermiso = idpermiso;
    }
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getPermiso() {
        return this.permiso;
    }
    
    public void setPermiso(String permiso) {
        this.permiso = permiso;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<UsuarioPermiso> getUsuarioPermisos() {
        return this.usuarioPermisos;
    }
    
    public void setUsuarioPermisos(Set<UsuarioPermiso> usuarioPermisos) {
        this.usuarioPermisos = usuarioPermisos;
    }




}


