package lissa.be;
// Generated 19/09/2018 05:49:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private long idpersona;
     private EstadoCivil estadoCivil;
     private TipoDocidentidad tipoDocidentidad;
     private TipoPersona tipoPersona;
     private String nombre;
     private String apellidoPaterno;
     private Date fechaNacimiento;
     private String numeroDocumento;
     private String apellidoMaterno;
     private Date fechaReg;
     private String direccion;
     private String telefono;
     private String gradoInstruccion;
     private String lugarNacimiento;
     private String lugarProcedencia;
     private String sexo;
     private String ocupacion;
     private Integer idUbigeo;
     private String correoElectronico;
     private byte[] foto;
     private String autorizaUsoDatos;
     private Integer estado;
     private String razonSocial;
     private String ruc;
     private int esproveedor;
     
     private Set<HistoriaClinica> historiaClinicas = new HashSet<HistoriaClinica>(0);
     private Set<PersonaEmpresa> personaEmpresas = new HashSet<PersonaEmpresa>(0);
     private Set<Atencion> atencions = new HashSet<Atencion>(0);
     private Set<FondoSolidaridad> fondoSolidaridads = new HashSet<FondoSolidaridad>(0);
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<Cita> citas = new HashSet<Cita>(0);
     private Set<Medico> medicos = new HashSet<Medico>(0);
     private Set<SeguroVidaUsaPersona> seguroVidaUsaPersonas = new HashSet<SeguroVidaUsaPersona>(0);

    public Persona() {
    }

	
    public Persona(long idpersona) {
        this.idpersona = idpersona;
    }
    public Persona(long idpersona, EstadoCivil estadoCivil, TipoDocidentidad tipoDocidentidad, String nombre, String apellidoPaterno, Date fechaNacimiento, String numeroDocumento, String apellidoMaterno, Date fechaReg, String direccion, String telefono, String gradoInstruccion, String lugarNacimiento, String lugarProcedencia, String sexo, String ocupacion, Integer idUbigeo, String correoElectronico, byte[] foto, String autorizaUsoDatos, Integer estado, Set<HistoriaClinica> historiaClinicas, Set<PersonaEmpresa> personaEmpresas, Set<Atencion> atencions, Set<FondoSolidaridad> fondoSolidaridads, Set<Usuario> usuarios, Set<Cita> citas, Set<Medico> medicos, Set<SeguroVidaUsaPersona> seguroVidaUsaPersonas) {
       this.idpersona = idpersona;
       this.estadoCivil = estadoCivil;
       this.tipoDocidentidad = tipoDocidentidad;
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.fechaNacimiento = fechaNacimiento;
       this.numeroDocumento = numeroDocumento;
       this.apellidoMaterno = apellidoMaterno;
       this.fechaReg = fechaReg;
       this.direccion = direccion;
       this.telefono = telefono;
       this.gradoInstruccion = gradoInstruccion;
       this.lugarNacimiento = lugarNacimiento;
       this.lugarProcedencia = lugarProcedencia;
       this.sexo = sexo;
       this.ocupacion = ocupacion;
       this.idUbigeo = idUbigeo;
       this.correoElectronico = correoElectronico;
       this.foto = foto;
       this.autorizaUsoDatos = autorizaUsoDatos;
       this.estado = estado;
       this.historiaClinicas = historiaClinicas;
       this.personaEmpresas = personaEmpresas;
       this.atencions = atencions;
       this.fondoSolidaridads = fondoSolidaridads;
       this.usuarios = usuarios;
       this.citas = citas;
       this.medicos = medicos;
       this.seguroVidaUsaPersonas = seguroVidaUsaPersonas;
    }
   
    public long getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(long idpersona) {
        this.idpersona = idpersona;
    }
    public EstadoCivil getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(EstadoCivil estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public TipoDocidentidad getTipoDocidentidad() {
        return this.tipoDocidentidad;
    }
    
    public void setTipoDocidentidad(TipoDocidentidad tipoDocidentidad) {
        this.tipoDocidentidad = tipoDocidentidad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getNumeroDocumento() {
        return this.numeroDocumento;
    }
    
    public void setNumeroDocumento(String numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getGradoInstruccion() {
        return this.gradoInstruccion;
    }
    
    public void setGradoInstruccion(String gradoInstruccion) {
        this.gradoInstruccion = gradoInstruccion;
    }
    public String getLugarNacimiento() {
        return this.lugarNacimiento;
    }
    
    public void setLugarNacimiento(String lugarNacimiento) {
        this.lugarNacimiento = lugarNacimiento;
    }
    public String getLugarProcedencia() {
        return this.lugarProcedencia;
    }
    
    public void setLugarProcedencia(String lugarProcedencia) {
        this.lugarProcedencia = lugarProcedencia;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getOcupacion() {
        return this.ocupacion;
    }
    
    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }
    public Integer getIdUbigeo() {
        return this.idUbigeo;
    }
    
    public void setIdUbigeo(Integer idUbigeo) {
        this.idUbigeo = idUbigeo;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public String getAutorizaUsoDatos() {
        return this.autorizaUsoDatos;
    }
    
    public void setAutorizaUsoDatos(String autorizaUsoDatos) {
        this.autorizaUsoDatos = autorizaUsoDatos;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Set<HistoriaClinica> getHistoriaClinicas() {
        return this.historiaClinicas;
    }
    
    public void setHistoriaClinicas(Set<HistoriaClinica> historiaClinicas) {
        this.historiaClinicas = historiaClinicas;
    }
    public Set<PersonaEmpresa> getPersonaEmpresas() {
        return this.personaEmpresas;
    }
    
    public void setPersonaEmpresas(Set<PersonaEmpresa> personaEmpresas) {
        this.personaEmpresas = personaEmpresas;
    }
    public Set<Atencion> getAtencions() {
        return this.atencions;
    }
    
    public void setAtencions(Set<Atencion> atencions) {
        this.atencions = atencions;
    }
    public Set<FondoSolidaridad> getFondoSolidaridads() {
        return this.fondoSolidaridads;
    }
    
    public void setFondoSolidaridads(Set<FondoSolidaridad> fondoSolidaridads) {
        this.fondoSolidaridads = fondoSolidaridads;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
    public Set<Cita> getCitas() {
        return this.citas;
    }
    
    public void setCitas(Set<Cita> citas) {
        this.citas = citas;
    }
    public Set<Medico> getMedicos() {
        return this.medicos;
    }
    
    public void setMedicos(Set<Medico> medicos) {
        this.medicos = medicos;
    }
    public Set<SeguroVidaUsaPersona> getSeguroVidaUsaPersonas() {
        return this.seguroVidaUsaPersonas;
    }
    
    public void setSeguroVidaUsaPersonas(Set<SeguroVidaUsaPersona> seguroVidaUsaPersonas) {
        this.seguroVidaUsaPersonas = seguroVidaUsaPersonas;
    }

    public String getRazonSocial() {
        return razonSocial;
    }

    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    public String getRuc() {
        return ruc;
    }

    public void setRuc(String ruc) {
        this.ruc = ruc;
    }

    public int getEsproveedor() {
        return esproveedor;
    }

    public void setEsproveedor(int esproveedor) {
        this.esproveedor = esproveedor;
    }

    public TipoPersona getTipoPersona() {
        return tipoPersona;
    }

    public void setTipoPersona(TipoPersona tipoPersona) {
        this.tipoPersona = tipoPersona;
    }




}


