package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PersonaEmpresa generated by hbm2java
 */
public class PersonaEmpresa  implements java.io.Serializable {


     private int idpersonaempresa;
     private Persona persona;
     private PersonaJuridica personaJuridica;
     private Date fechaRegistro;

    public PersonaEmpresa() {
    }

	
    public PersonaEmpresa(int idpersonaempresa, Persona persona, PersonaJuridica personaJuridica) {
        this.idpersonaempresa = idpersonaempresa;
        this.persona = persona;
        this.personaJuridica = personaJuridica;
    }
    public PersonaEmpresa(int idpersonaempresa, Persona persona, PersonaJuridica personaJuridica, Date fechaRegistro) {
       this.idpersonaempresa = idpersonaempresa;
       this.persona = persona;
       this.personaJuridica = personaJuridica;
       this.fechaRegistro = fechaRegistro;
    }
   
    public int getIdpersonaempresa() {
        return this.idpersonaempresa;
    }
    
    public void setIdpersonaempresa(int idpersonaempresa) {
        this.idpersonaempresa = idpersonaempresa;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public PersonaJuridica getPersonaJuridica() {
        return this.personaJuridica;
    }
    
    public void setPersonaJuridica(PersonaJuridica personaJuridica) {
        this.personaJuridica = personaJuridica;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }




}


