package lissa.be;
// Generated 19/04/2018 04:37:19 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * PrecioProducto generated by hbm2java
 */
public class PrecioProducto  implements java.io.Serializable {


     private long idprecioproducto;
     private AlmacenProducto almacenProducto;
     private BigDecimal pvMin;
     private BigDecimal pvMax;
     private BigDecimal pvSugerido;
     private Date fechaInicio;
     private Date fechaFin;
     private long idUsuario;
     private int estado;

    public PrecioProducto() {
    }

	
    public PrecioProducto(long idprecioproducto, AlmacenProducto almacenProducto, Date fechaInicio, long idUsuario, int estado) {
        this.idprecioproducto = idprecioproducto;
        this.almacenProducto = almacenProducto;
        this.fechaInicio = fechaInicio;
        this.idUsuario = idUsuario;
        this.estado = estado;
    }
    public PrecioProducto(long idprecioproducto, AlmacenProducto almacenProducto, BigDecimal pvMin, BigDecimal pvMax, BigDecimal pvSugerido, Date fechaInicio, Date fechaFin, long idUsuario, int estado) {
       this.idprecioproducto = idprecioproducto;
       this.almacenProducto = almacenProducto;
       this.pvMin = pvMin;
       this.pvMax = pvMax;
       this.pvSugerido = pvSugerido;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.idUsuario = idUsuario;
       this.estado = estado;
    }
   
    public long getIdprecioproducto() {
        return this.idprecioproducto;
    }
    
    public void setIdprecioproducto(long idprecioproducto) {
        this.idprecioproducto = idprecioproducto;
    }
    public AlmacenProducto getAlmacenProducto() {
        return this.almacenProducto;
    }
    
    public void setAlmacenProducto(AlmacenProducto almacenProducto) {
        this.almacenProducto = almacenProducto;
    }
    public BigDecimal getPvMin() {
        return this.pvMin;
    }
    
    public void setPvMin(BigDecimal pvMin) {
        this.pvMin = pvMin;
    }
    public BigDecimal getPvMax() {
        return this.pvMax;
    }
    
    public void setPvMax(BigDecimal pvMax) {
        this.pvMax = pvMax;
    }
    public BigDecimal getPvSugerido() {
        return this.pvSugerido;
    }
    
    public void setPvSugerido(BigDecimal pvSugerido) {
        this.pvSugerido = pvSugerido;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public long getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(long idUsuario) {
        this.idUsuario = idUsuario;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }




}


