package lissa.be;
// Generated 09/10/2018 05:16:30 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;




/**
 * ProcedimientoTarifario generated by hbm2java
 */
public class ProcedimientoTarifario  implements java.io.Serializable {


     private long idprocedimientotarifario;
     private Procedimiento procedimiento;
     private Tarifario tarifario;
     private BigDecimal costo;
     private int estado;

    public ProcedimientoTarifario() {
    }

    public ProcedimientoTarifario(long idprocedimientotarifario, Procedimiento procedimiento, Tarifario tarifario) {
       this.idprocedimientotarifario = idprocedimientotarifario;
       this.procedimiento = procedimiento;
       this.tarifario = tarifario;
    }
   
    public long getIdprocedimientotarifario() {
        return this.idprocedimientotarifario;
    }
    
    public void setIdprocedimientotarifario(long idprocedimientotarifario) {
        this.idprocedimientotarifario = idprocedimientotarifario;
    }
    public Procedimiento getProcedimiento() {
        return this.procedimiento;
    }
    
    public void setProcedimiento(Procedimiento procedimiento) {
        this.procedimiento = procedimiento;
    }
    public Tarifario getTarifario() {
        return this.tarifario;
    }
    
    public void setTarifario(Tarifario tarifario) {
        this.tarifario = tarifario;
    }

    public BigDecimal getCosto() {
        return costo;
    }

    public void setCosto(BigDecimal costo) {
        this.costo = costo;
    }

    public int getEstado() {
        return estado;
    }

    public void setEstado(int estado) {
        this.estado = estado;
    }




}


