package lissa.be;
// Generated 19/04/2018 04:37:19 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

    private long idproducto;
    private FormaFarmaceutica formaFarmaceutica;
    private Laboratorio laboratorio;
    private Presentacion presentacion;
    private String nombre;
    private String codigo;
    private String concentracion;
    private Integer fraccion;
    private String nombreGenerico;
    private Set<DetalleCompra> detalleCompras = new HashSet<DetalleCompra>(0);
    private Set<AlmacenProducto> almacenProductos = new HashSet<AlmacenProducto>(0);
    private Set<DetalleVenta> detalleVentas = new HashSet<DetalleVenta>(0);
    private int op = -1;
    public static final int DEFECTO = -1, DATO = 3;

    public Producto() {
    }

    public long getIdproducto() {
        return this.idproducto;
    }

    public void setIdproducto(long idproducto) {
        this.idproducto = idproducto;
    }

    public FormaFarmaceutica getFormaFarmaceutica() {
        return this.formaFarmaceutica;
    }

    public void setFormaFarmaceutica(FormaFarmaceutica formaFarmaceutica) {
        this.formaFarmaceutica = formaFarmaceutica;
    }

    public Laboratorio getLaboratorio() {
        return this.laboratorio;
    }

    public void setLaboratorio(Laboratorio laboratorio) {
        this.laboratorio = laboratorio;
    }

    public Presentacion getPresentacion() {
        return this.presentacion;
    }

    public void setPresentacion(Presentacion presentacion) {
        this.presentacion = presentacion;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getConcentracion() {
        return this.concentracion;
    }

    public void setConcentracion(String concentracion) {
        this.concentracion = concentracion;
    }

    public Integer getFraccion() {
        return this.fraccion;
    }

    public void setFraccion(Integer fraccion) {
        this.fraccion = fraccion;
    }

    public String getNombreGenerico() {
        return this.nombreGenerico;
    }

    public void setNombreGenerico(String nombreGenerico) {
        this.nombreGenerico = nombreGenerico;
    }

    public Set<DetalleCompra> getDetalleCompras() {
        return this.detalleCompras;
    }

    public void setDetalleCompras(Set<DetalleCompra> detalleCompras) {
        this.detalleCompras = detalleCompras;
    }

    public Set<AlmacenProducto> getAlmacenProductos() {
        return this.almacenProductos;
    }

    public void setAlmacenProductos(Set<AlmacenProducto> almacenProductos) {
        this.almacenProductos = almacenProductos;
    }

    public Set<DetalleVenta> getDetalleVentas() {
        return this.detalleVentas;
    }

    public void setDetalleVentas(Set<DetalleVenta> detalleVentas) {
        this.detalleVentas = detalleVentas;
    }

    public int getOp() {
        return op;
    }

    public void setOp(int op) {
        this.op = op;
    }

    @Override
    public String toString() {
        switch (getOp()) {
            case DATO:
                return getNombre();
            default:
                return "<Seleccione>";

        }
    }

}
