package lissa.be;
// Generated 09-sep-2016 12:25:59 by Hibernate Tools 4.3.1

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private long idproveedor;
     private PersonaJuridica personaJuridica;
     private String estado;
   
    public static final int DEFECTO = -1, DATO = 3;
    private int op = -1;
    
    public Proveedor() {
    }

   
    public long getIdproveedor() {
        return this.idproveedor;
    }
    
    public void setIdproveedor(long idproveedor) {
        this.idproveedor = idproveedor;
    }
    public PersonaJuridica getPersonaJuridica() {
        return this.personaJuridica;
    }
    
    public void setPersonaJuridica(PersonaJuridica personaJuridica) {
        this.personaJuridica = personaJuridica;
    }
    public int getOp() {
        return op;
    }

    public void setOp(int op) {
        this.op = op;
    }
    @Override
    public String toString() {
        switch (op) {
            case DATO:
                return getPersonaJuridica().getRazonSocial();
            default:
                return "<SELECCIONE>";
        }
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }



}


