package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private int idrol;
     private String denominacion;
     private String descripcion;
     private Boolean estado;
     private Date fechaReg;
     private Set<UsuarioRol> usuarioRols = new HashSet<UsuarioRol>(0);
     public static final int DEFECTO = -1, DATO = 3;
     private int op = -1;

    public Rol() {
    }

	
    public Rol(int idrol) {
        this.idrol = idrol;
    }
    public Rol(int idrol, String denominacion, String descripcion, Boolean estado, Date fechaReg, Set<UsuarioRol> usuarioRols) {
       this.idrol = idrol;
       this.denominacion = denominacion;
       this.descripcion = descripcion;
       this.estado = estado;
       this.fechaReg = fechaReg;
       this.usuarioRols = usuarioRols;
    }
   
    public int getIdrol() {
        return this.idrol;
    }
    
    public void setIdrol(int idrol) {
        this.idrol = idrol;
    }
    public String getDenominacion() {
        return this.denominacion;
    }
    
    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public Set<UsuarioRol> getUsuarioRols() {
        return this.usuarioRols;
    }
    
    public void setUsuarioRols(Set<UsuarioRol> usuarioRols) {
        this.usuarioRols = usuarioRols;
    }

    public int getOp() {
        return op;
    }

    public void setOp(int op) {
        this.op = op;
    }

    @Override
    public String toString() {
        switch (op) {
            case DATO:
                return getDenominacion();
            default:
                return "<SELECCIONE>";
        }
    }


}


