package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SeguroVidaUsaPersona generated by hbm2java
 */
public class SeguroVidaUsaPersona  implements java.io.Serializable {


     private int idSeguroVidaUsaPersona;
     private Persona persona;
     private SeguroVida seguroVida;
     private Date fechaReg;
     private Boolean estado;

    public SeguroVidaUsaPersona() {
    }

	
    public SeguroVidaUsaPersona(int idSeguroVidaUsaPersona) {
        this.idSeguroVidaUsaPersona = idSeguroVidaUsaPersona;
    }
    public SeguroVidaUsaPersona(int idSeguroVidaUsaPersona, Persona persona, SeguroVida seguroVida, Date fechaReg, Boolean estado) {
       this.idSeguroVidaUsaPersona = idSeguroVidaUsaPersona;
       this.persona = persona;
       this.seguroVida = seguroVida;
       this.fechaReg = fechaReg;
       this.estado = estado;
    }
   
    public int getIdSeguroVidaUsaPersona() {
        return this.idSeguroVidaUsaPersona;
    }
    
    public void setIdSeguroVidaUsaPersona(int idSeguroVidaUsaPersona) {
        this.idSeguroVidaUsaPersona = idSeguroVidaUsaPersona;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public SeguroVida getSeguroVida() {
        return this.seguroVida;
    }
    
    public void setSeguroVida(SeguroVida seguroVida) {
        this.seguroVida = seguroVida;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


