package lissa.be;
// Generated 14/06/2017 04:06:49 PM by Hibernate Tools 4.3.1



/**
 * ServiciosFondoSolidaridad generated by hbm2java
 */
public class ServiciosFondoSolidaridad  implements java.io.Serializable {


     private int idserviciosfs;
     private FondoSolidaridad fondoSolidaridad;
     private PaqueteFondoSolidaridad paqueteFondoSolidaridad;
     private String estado;

    public ServiciosFondoSolidaridad() {
    }

    public ServiciosFondoSolidaridad(int idserviciosfs, FondoSolidaridad fondoSolidaridad, PaqueteFondoSolidaridad paqueteFondoSolidaridad) {
       this.idserviciosfs = idserviciosfs;
       this.fondoSolidaridad = fondoSolidaridad;
       this.paqueteFondoSolidaridad = paqueteFondoSolidaridad;
    }
   
    public int getIdserviciosfs() {
        return this.idserviciosfs;
    }
    
    public void setIdserviciosfs(int idserviciosfs) {
        this.idserviciosfs = idserviciosfs;
    }
    public FondoSolidaridad getFondoSolidaridad() {
        return this.fondoSolidaridad;
    }
    
    public void setFondoSolidaridad(FondoSolidaridad fondoSolidaridad) {
        this.fondoSolidaridad = fondoSolidaridad;
    }
    public PaqueteFondoSolidaridad getPaqueteFondoSolidaridad() {
        return this.paqueteFondoSolidaridad;
    }
    
    public void setPaqueteFondoSolidaridad(PaqueteFondoSolidaridad paqueteFondoSolidaridad) {
        this.paqueteFondoSolidaridad = paqueteFondoSolidaridad;
    }
    
    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }




}


