package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Servicio generated by hbm2java
 */
public class Servicio implements java.io.Serializable {

    private long idservicio;
    private String denominacion;
    private String codigo;
    private Date fechaReg;
    private int estado;
    private Set<Procedimiento> procedimientos = new HashSet<Procedimiento>(0);
    public static final int DEFECTO = -1, DATO = 3;
    private int op = -1;

    public Servicio() {
    }

    public long getIdservicio() {
        return this.idservicio;
    }

    public void setIdservicio(long idservicio) {
        this.idservicio = idservicio;
    }
    public String getDenominacion() {
        return this.denominacion;
    }

    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public Date getFechaReg() {
        return this.fechaReg;
    }

    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }

    public int getEstado() {
        return this.estado;
    }

    public void setEstado(int estado) {
        this.estado = estado;
    }

    public Set<Procedimiento> getProcedimientos() {
        return this.procedimientos;
    }

    public void setProcedimientos(Set<Procedimiento> procedimientos) {
        this.procedimientos = procedimientos;
    }

    public int getOp() {
        return op;
    }

    public void setOp(int op) {
        this.op = op;
    }

    @Override
    public String toString() {
        switch (op) {
            case DATO:
                return getDenominacion();
            default:
                return "<SELECCIONE>";
        }
    }

}
