package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * TipoDocidentidad generated by hbm2java
 */
public class TipoDocidentidad implements java.io.Serializable {

    private long idtipodocidentidad;
    private String documento;
    private Boolean estado;
    private String codigoSunat;
    private Set<Persona> personas = new HashSet<Persona>(0);
    public static final int DEFECTO = -1, DATO = 3;
    private int op = -1;

    public TipoDocidentidad() {
    }

    public TipoDocidentidad(long idtipodocidentidad, String documento) {
        this.idtipodocidentidad = idtipodocidentidad;
        this.documento = documento;
    }

    public TipoDocidentidad(long idtipodocidentidad, String documento, Boolean estado, Set<Persona> personas) {
        this.idtipodocidentidad = idtipodocidentidad;
        this.documento = documento;
        this.estado = estado;
        this.personas = personas;
    }

    public long getIdtipodocidentidad() {
        return this.idtipodocidentidad;
    }

    public void setIdtipodocidentidad(long idtipodocidentidad) {
        this.idtipodocidentidad = idtipodocidentidad;
    }

    public String getDocumento() {
        return this.documento;
    }

    public void setDocumento(String documento) {
        this.documento = documento;
    }

    public Boolean getEstado() {
        return this.estado;
    }

    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    public Set<Persona> getPersonas() {
        return this.personas;
    }

    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }

    public int getOp() {
        return op;
    }

    public void setOp(int op) {
        this.op = op;
    }

    @Override
    public String toString() {
        switch (op) {
            case DATO:
                return getDocumento();
            default:
                return "<SELECCIONE>";
        }
    }

    public String getCodigoSunat() {
        return codigoSunat;
    }

    public void setCodigoSunat(String codigoSunat) {
        this.codigoSunat = codigoSunat;
    }

}
