package lissa.be;
// Generated 04/01/2019 08:56:25 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * TipoPersona generated by hbm2java
 */
public class TipoPersona implements java.io.Serializable {

    private long idtipopersona;
    private String descripcion;
    private int estado;
    private Set<Persona> personas = new HashSet<Persona>(0);
    public static final int DATO = 1, DEFAULT = 2;
    private int op = -1;

    public TipoPersona() {
    }

    public TipoPersona(long idtipopersona, String descripcion, int estado) {
        this.idtipopersona = idtipopersona;
        this.descripcion = descripcion;
        this.estado = estado;
    }

    public TipoPersona(long idtipopersona, String descripcion, int estado, Set<Persona> personas) {
        this.idtipopersona = idtipopersona;
        this.descripcion = descripcion;
        this.estado = estado;
        this.personas = personas;
    }

    public long getIdtipopersona() {
        return this.idtipopersona;
    }

    public void setIdtipopersona(long idtipopersona) {
        this.idtipopersona = idtipopersona;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public int getEstado() {
        return this.estado;
    }

    public void setEstado(int estado) {
        this.estado = estado;
    }

    public Set<Persona> getPersonas() {
        return this.personas;
    }

    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }

    public int getOp() {
        return op;
    }

    public void setOp(int op) {
        this.op = op;
    }
    
    @Override
    public String toString() {
        switch (getOp()) {
            case DATO:
                return getDescripcion();
            default:
                return "<SELECCIONE>";
        }
    }

}
