package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * TipoMedico generated by hbm2java
 */
public class TipoMedico implements java.io.Serializable {

    private int idTipoMedico;
    private String nombre;
    private String descripcion;
    private Set<Medico> medicos = new HashSet<Medico>(0);
    public static final int DEFECTO = -1, DATO = 3;
    private int op = -1;

    public TipoMedico() {
    }

    public TipoMedico(int idTipoMedico) {
        this.idTipoMedico = idTipoMedico;
    }

    public TipoMedico(int idTipoMedico, String nombre, String descripcion, Set<Medico> medicos) {
        this.idTipoMedico = idTipoMedico;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.medicos = medicos;
    }

    public int getIdTipoMedico() {
        return this.idTipoMedico;
    }

    public void setIdTipoMedico(int idTipoMedico) {
        this.idTipoMedico = idTipoMedico;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Set<Medico> getMedicos() {
        return this.medicos;
    }

    public void setMedicos(Set<Medico> medicos) {
        this.medicos = medicos;
    }

    public int getOp() {
        return op;
    }

    public void setOp(int op) {
        this.op = op;
    }

    @Override
    public String toString() {
        switch (op) {
            case DATO:
                return getNombre();
            default:
                return "<SELECCIONE>";
        }
    }

}
