package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private long idUsuario;
     private Persona persona;
     private String nombre;
     private String descripcion;
     private String contrasenia;
     private Boolean estado;
     private Date fechaReg;
     private Set<Caja> cajas = new HashSet<Caja>(0);
     private Set<UsuarioRol> usuarioRols = new HashSet<UsuarioRol>(0);
     private Set<UsuarioPermiso> usuarioPermisos = new HashSet<UsuarioPermiso>(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Usuario(int idUsuario, Persona persona, String nombre, String descripcion, String contrasenia, Boolean estado, Date fechaReg, Set<Caja> cajas, Set<UsuarioRol> usuarioRols) {
       this.idUsuario = idUsuario;
       this.persona = persona;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.contrasenia = contrasenia;
       this.estado = estado;
       this.fechaReg = fechaReg;
       this.cajas = cajas;
       this.usuarioRols = usuarioRols;
    }
   
    public long getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(long idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public Set<Caja> getCajas() {
        return this.cajas;
    }
    
    public void setCajas(Set<Caja> cajas) {
        this.cajas = cajas;
    }
    public Set<UsuarioRol> getUsuarioRols() {
        return this.usuarioRols;
    }
    
    public void setUsuarioRols(Set<UsuarioRol> usuarioRols) {
        this.usuarioRols = usuarioRols;
    }
    public Set<UsuarioPermiso> getUsuarioPermisos() {
        return usuarioPermisos;
    }

    public void setUsuarioPermisos(Set<UsuarioPermiso> usuarioPermisos) {
        this.usuarioPermisos = usuarioPermisos;
    }




}


