package lissa.be;
// Generated 14-abr-2016 18:27:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UsuarioRol generated by hbm2java
 */
public class UsuarioRol  implements java.io.Serializable {


     private int idUsuarioRol;
     private Rol rol;
     private Usuario usuario;
     private Date fechaReg;
     private String descripcion;
     private int estado;

    public UsuarioRol() {
    }

	
    public UsuarioRol(int idUsuarioRol) {
        this.idUsuarioRol = idUsuarioRol;
    }
    public UsuarioRol(int idUsuarioRol, Rol rol, Usuario usuario, Date fechaReg, String descripcion, int estado) {
       this.idUsuarioRol = idUsuarioRol;
       this.rol = rol;
       this.usuario = usuario;
       this.fechaReg = fechaReg;
       this.descripcion = descripcion;
       this.estado = estado;
    }
   
    public int getIdUsuarioRol() {
        return this.idUsuarioRol;
    }
    
    public void setIdUsuarioRol(int idUsuarioRol) {
        this.idUsuarioRol = idUsuarioRol;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }




}


