package lissa.be;
// Generated 19-oct-2016 12:42:31 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta implements java.io.Serializable {

    private long idventa;
    private Organizacion organizacion;
    private FarComprobante farComprobante;
    private TipoDocidentidad tipoDocCliente;
    private Persona clientepersonanatural;
    private Persona personaPaciente;
    private Usuario usuarioReg;
    private Usuario usuarioAnu;
    private Caja caja;
    private AreaConsumo areaConsumo;
    private Almacen almacenOrigen;
    private Date fechaVenta;
    private String horaVenta;
    private Long numComprobante;
    private int grupoNumeracion;
    private BigDecimal subTotal;
    private BigDecimal montoIgv;
    private BigDecimal total;
    private String estado;
    private String motivoAnulacion;
    private int numOperacion;    
    private String descripcionSeguros;    
    private String observacion;
    //variables para la fact electronica
    private String serie;
    private BigDecimal tipoCambio;
    private BigDecimal totalValorVentaOpGravadas;
    private BigDecimal totalValorVentaOpeInafectas;
    private BigDecimal totalValorVentaOpeExoneradas;
    private BigDecimal totalSumatoriaIgv;
    private BigDecimal totalSumatoriaIsc;
    private BigDecimal totalSumatoriaOtrosTributos;
    private BigDecimal totalSumatoriaOtrosCargos;
    private BigDecimal totalSumatoriaDescuentos;
    private BigDecimal totalImporteVenta;
    private String tipoMoneda;
    private BigDecimal totalOpeGratuitas;
    private String responsableNotasalida;
    private String correoClienteTemp;
    private String estadoSunat;
    private Set<DetalleVenta> detalleVentas = new HashSet<DetalleVenta>(0);
    private Set<Cuentaxcobrar> cuentaxcobrars = new HashSet<Cuentaxcobrar>(0);

    public Venta() {
    }

    public long getIdventa() {
        return this.idventa;
    }

    public void setIdventa(long idventa) {
        this.idventa = idventa;
    }    

    public Date getFechaVenta() {
        return this.fechaVenta;
    }

    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }

    public String getHoraVenta() {
        return this.horaVenta;
    }

    public void setHoraVenta(String horaVenta) {
        this.horaVenta = horaVenta;
    }

    public Long getNumComprobante() {
        return this.numComprobante;
    }

    public void setNumComprobante(Long numComprobante) {
        this.numComprobante = numComprobante;
    }

    public int getGrupoNumeracion() {
        return this.grupoNumeracion;
    }

    public void setGrupoNumeracion(int grupoNumeracion) {
        this.grupoNumeracion = grupoNumeracion;
    }

    public BigDecimal getSubTotal() {
        return this.subTotal;
    }

    public void setSubTotal(BigDecimal subTotal) {
        this.subTotal = subTotal;
    }

    public BigDecimal getMontoIgv() {
        return this.montoIgv;
    }

    public void setMontoIgv(BigDecimal montoIgv) {
        this.montoIgv = montoIgv;
    }

    public BigDecimal getTotal() {
        return this.total;
    }

    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public String getMotivoAnulacion() {
        return this.motivoAnulacion;
    }

    public void setMotivoAnulacion(String motivoAnulacion) {
        this.motivoAnulacion = motivoAnulacion;
    }

    public int getNumOperacion() {
        return this.numOperacion;
    }

    public void setNumOperacion(int numOperacion) {
        this.numOperacion = numOperacion;
    }

    public Set<DetalleVenta> getDetalleVentas() {
        return this.detalleVentas;
    }

    public void setDetalleVentas(Set<DetalleVenta> detalleVentas) {
        this.detalleVentas = detalleVentas;
    }

    public FarComprobante getFarComprobante() {
        return farComprobante;
    }

    public void setFarComprobante(FarComprobante farComprobante) {
        this.farComprobante = farComprobante;
    }

    public String getDescripcionSeguros() {
        return descripcionSeguros;
    }

    public void setDescripcionSeguros(String descripcionSeguros) {
        this.descripcionSeguros = descripcionSeguros;
    }

    public Set<Cuentaxcobrar> getCuentaxcobrars() {
        return cuentaxcobrars;
    }

    public void setCuentaxcobrars(Set<Cuentaxcobrar> cuentaxcobrars) {
        this.cuentaxcobrars = cuentaxcobrars;
    }

    public AreaConsumo getAreaConsumo() {
        return areaConsumo;
    }

    public void setAreaConsumo(AreaConsumo areaConsumo) {
        this.areaConsumo = areaConsumo;
    }

    public String getResponsableNotasalida() {
        return this.responsableNotasalida;
    }

    public void setResponsableNotasalida(String responsableNotasalida) {
        this.responsableNotasalida = responsableNotasalida;
    }

    public Almacen getAlmacenOrigen() {
        return almacenOrigen;
    }

    public void setAlmacenOrigen(Almacen almacenOrigen) {
        this.almacenOrigen = almacenOrigen;
    }

    public String getObservacion() {
        return observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    public BigDecimal getTipoCambio() {
        return tipoCambio;
    }

    public void setTipoCambio(BigDecimal tipoCambio) {
        this.tipoCambio = tipoCambio;
    }

    public BigDecimal getTotalValorVentaOpGravadas() {
        return totalValorVentaOpGravadas;
    }

    public void setTotalValorVentaOpGravadas(BigDecimal totalValorVentaOpGravadas) {
        this.totalValorVentaOpGravadas = totalValorVentaOpGravadas;
    }

    public BigDecimal getTotalValorVentaOpeInafectas() {
        return totalValorVentaOpeInafectas;
    }

    public void setTotalValorVentaOpeInafectas(BigDecimal totalValorVentaOpeInafectas) {
        this.totalValorVentaOpeInafectas = totalValorVentaOpeInafectas;
    }

    public BigDecimal getTotalValorVentaOpeExoneradas() {
        return totalValorVentaOpeExoneradas;
    }

    public void setTotalValorVentaOpeExoneradas(BigDecimal totalValorVentaOpeExoneradas) {
        this.totalValorVentaOpeExoneradas = totalValorVentaOpeExoneradas;
    }

    public BigDecimal getTotalSumatoriaIgv() {
        return totalSumatoriaIgv;
    }

    public void setTotalSumatoriaIgv(BigDecimal totalSumatoriaIgv) {
        this.totalSumatoriaIgv = totalSumatoriaIgv;
    }

    public BigDecimal getTotalSumatoriaIsc() {
        return totalSumatoriaIsc;
    }

    public void setTotalSumatoriaIsc(BigDecimal totalSumatoriaIsc) {
        this.totalSumatoriaIsc = totalSumatoriaIsc;
    }

    public BigDecimal getTotalSumatoriaOtrosTributos() {
        return totalSumatoriaOtrosTributos;
    }

    public void setTotalSumatoriaOtrosTributos(BigDecimal totalSumatoriaOtrosTributos) {
        this.totalSumatoriaOtrosTributos = totalSumatoriaOtrosTributos;
    }

    public BigDecimal getTotalSumatoriaOtrosCargos() {
        return totalSumatoriaOtrosCargos;
    }

    public void setTotalSumatoriaOtrosCargos(BigDecimal totalSumatoriaOtrosCargos) {
        this.totalSumatoriaOtrosCargos = totalSumatoriaOtrosCargos;
    }

    public BigDecimal getTotalSumatoriaDescuentos() {
        return totalSumatoriaDescuentos;
    }

    public void setTotalSumatoriaDescuentos(BigDecimal totalSumatoriaDescuentos) {
        this.totalSumatoriaDescuentos = totalSumatoriaDescuentos;
    }

    public BigDecimal getTotalImporteVenta() {
        return totalImporteVenta;
    }

    public void setTotalImporteVenta(BigDecimal totalImporteVenta) {
        this.totalImporteVenta = totalImporteVenta;
    }

    public String getTipoMoneda() {
        return tipoMoneda;
    }

    public void setTipoMoneda(String tipoMoneda) {
        this.tipoMoneda = tipoMoneda;
    }

    public BigDecimal getTotalOpeGratuitas() {
        return totalOpeGratuitas;
    }

    public void setTotalOpeGratuitas(BigDecimal totalOpeGratuitas) {
        this.totalOpeGratuitas = totalOpeGratuitas;
    }

    public Organizacion getOrganizacion() {
        return organizacion;
    }

    public void setOrganizacion(Organizacion organizacion) {
        this.organizacion = organizacion;
    }

    public TipoDocidentidad getTipoDocCliente() {
        return tipoDocCliente;
    }

    public void setTipoDocCliente(TipoDocidentidad tipoDocCliente) {
        this.tipoDocCliente = tipoDocCliente;
    }

    public Persona getClientepersonanatural() {
        return clientepersonanatural;
    }

    public void setClientepersonanatural(Persona clientepersonanatural) {
        this.clientepersonanatural = clientepersonanatural;
    }

    public String getSerie() {
        return serie;
    }

    public void setSerie(String serie) {
        this.serie = serie;
    }

    public Persona getPersonaPaciente() {
        return personaPaciente;
    }

    public void setPersonaPaciente(Persona personaPaciente) {
        this.personaPaciente = personaPaciente;
    }

    public Usuario getUsuarioReg() {
        return usuarioReg;
    }

    public void setUsuarioReg(Usuario usuarioReg) {
        this.usuarioReg = usuarioReg;
    }

    public Usuario getUsuarioAnu() {
        return usuarioAnu;
    }

    public void setUsuarioAnu(Usuario usuarioAnu) {
        this.usuarioAnu = usuarioAnu;
    }

    public Caja getCaja() {
        return caja;
    }

    public void setCaja(Caja caja) {
        this.caja = caja;
    }

    public String getCorreoClienteTemp() {
        return correoClienteTemp;
    }

    public void setCorreoClienteTemp(String correoClienteTemp) {
        this.correoClienteTemp = correoClienteTemp;
    }

    public String getEstadoSunat() {
        return estadoSunat;
    }

    public void setEstadoSunat(String estadoSunat) {
        this.estadoSunat = estadoSunat;
    }
}
