package lissa.gui;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import lissa.be.Persona;
import lissa.be.PersonaEmpresa;
import lissa.be.PersonaJuridica;
import lissa.be.Proveedor;
import lissa.bl.PersonaBl;
import lissa.bl.PersonaEmpresaBl;
import lissa.bl.PersonaJuridicaBl;
import lissa.bl.ProveedorBl;
import lissa.dao.PersonaEmpresaDao;
import lissa.table.ModeloPersonaJuridica;
import lissa.util.Mensajes;
import lissa.util.Utilitarios;

public class JIF_AdministrarPersonaJuridica extends javax.swing.JInternalFrame {

    private JF_Principal root;

    private PersonaJuridica oPersonaJuridica;
    private PersonaJuridicaBl oPersonaJuridicaBl;
    private Proveedor oProveedor;
    private ProveedorBl oProveedorBl;
    private Persona oPersona;
    private PersonaBl oPersonaBl;
    private ModeloPersonaJuridica oModeloPersonaJuridica;
    private ArrayList<PersonaJuridica> listPersona;
    private PersonaJuridica beanTabla;
    private PersonaEmpresa oPersonaEmpresa;
    private PersonaEmpresaBl oPersonaEmpresaBl;
    private int banBoton = 0;

    private int invocador;

    public static final int JIF_EMITIR_COMPROBANTE = 1;
    public static final int JIF_EMITIR_COMPROBANTE2 = 2;
    public static final int JIF_VENTAS = 3;

    public JIF_AdministrarPersonaJuridica(JF_Principal root) {
        initComponents();
        this.root = root;
        oModeloPersonaJuridica = new ModeloPersonaJuridica();
        tblResultados.setModel(oModeloPersonaJuridica);
        resetComponent();
        estadoTextFields(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txfBusqRuc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();
        txfBusqRazonSocial = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txfDireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txfRazonSocial = new javax.swing.JTextField();
        txfNumeroRuc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txfTelefono = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txfActividadEconomica = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        chbxProveedor = new javax.swing.JCheckBox();
        btnEditar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Administración de personas juridicas");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Búsqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        txfBusqRuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfBusqRucActionPerformed(evt);
            }
        });
        txfBusqRuc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txfBusqRucKeyPressed(evt);
            }
        });

        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblResultadosMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblResultados);

        txfBusqRazonSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfBusqRazonSocialActionPerformed(evt);
            }
        });
        txfBusqRazonSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txfBusqRazonSocialKeyPressed(evt);
            }
        });

        jLabel2.setText("N° Ruc");

        jLabel8.setText("Razón Social");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfBusqRuc)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 74, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(259, 259, 259))
                    .addComponent(txfBusqRazonSocial)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfBusqRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfBusqRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txfBusqRuc.getAccessibleContext().setAccessibleName("");

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lissa/resources/cancel.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lissa/resources/Save.png"))); // NOI18N
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la Empresa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Dirección :");

        txfDireccion.setEnabled(false);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Razón Social :");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Numero RUC :");

        txfRazonSocial.setEnabled(false);

        txfNumeroRuc.setEnabled(false);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Teléfono :");

        txfTelefono.setEnabled(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Actividad Económica :");

        txfActividadEconomica.setEnabled(false);

        jLabel9.setText("Proveedor :");

        chbxProveedor.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfTelefono)
                    .addComponent(txfNumeroRuc)
                    .addComponent(txfRazonSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addComponent(txfActividadEconomica)
                    .addComponent(txfDireccion)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(chbxProveedor)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txfRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txfNumeroRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txfActividadEconomica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(chbxProveedor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lissa/resources/edit.png"))); // NOI18N
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lissa/resources/new.png"))); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lissa/resources/arrow.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 212, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar)
                            .addComponent(btnGuardar)
                            .addComponent(btnEditar)
                            .addComponent(btnNuevo)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7)))
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblResultadosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResultadosMouseReleased
        if (tblResultados.getRowSelectionAllowed()) {
            obtenerDatosTabla();
            estadoTextFields(false);
            this.btnEditar.setEnabled(true);
            //btnCancelar.setEnabled(true);

        }
    }//GEN-LAST:event_tblResultadosMouseReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (beanTabla == null || beanTabla.getIdPersonaJuridica() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione una persona", "Atencion", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (isDatosValidos()) {
                cargarDatosPersona();
                this.doDefaultCloseAction();
                oModeloPersonaJuridica.clear();
                beanTabla = null;
            } else {
                JOptionPane.showMessageDialog(null, "Actualice la informacion de la persona antes de cargar", "Atencion", JOptionPane.INFORMATION_MESSAGE);
                //paintComponent();
                //configuraModificar();
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        configuraCancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        configuraGuardar();
        personalizarTabla();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        configuraNuevo();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tblResultados.getSelectedRow() != -1) {
            configuraActualizar();
        } else {
            JOptionPane.showMessageDialog(null, "Por favor seleccione un item", "ATENCION", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        resetComponent();
    }//GEN-LAST:event_formInternalFrameClosing

    private void txfBusqRucKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfBusqRucKeyPressed
        oModeloPersonaJuridica.clear();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txfBusqRuc.getText().trim().equals("")) {
                buscarPersonaJuridicaRuc();
            } else {
                Mensajes.msjParametroVacio();
            }
        }
    }//GEN-LAST:event_txfBusqRucKeyPressed

    private void txfBusqRazonSocialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfBusqRazonSocialKeyPressed
        oModeloPersonaJuridica.clear();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txfBusqRazonSocial.getText().toUpperCase().trim().equals("")) {
                buscarPersonaJuridicaxNombre();
            } else {
                Mensajes.msjParametroVacio();
            }
        }
    }//GEN-LAST:event_txfBusqRazonSocialKeyPressed

    private void txfBusqRucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfBusqRucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfBusqRucActionPerformed

    private void txfBusqRazonSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfBusqRazonSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfBusqRazonSocialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JCheckBox chbxProveedor;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResultados;
    private javax.swing.JTextField txfActividadEconomica;
    private javax.swing.JTextField txfBusqRazonSocial;
    private javax.swing.JTextField txfBusqRuc;
    private javax.swing.JTextField txfDireccion;
    private javax.swing.JTextField txfNumeroRuc;
    private javax.swing.JTextField txfRazonSocial;
    private javax.swing.JTextField txfTelefono;
    // End of variables declaration//GEN-END:variables

    private void buscarPersonaJuridica() {
        oPersonaJuridicaBl = new PersonaJuridicaBl();
        String ref = txfBusqRuc.getText().trim().toUpperCase();
        listPersona = oPersonaJuridicaBl.buscarPersonaJuridica(ref);
        if (listPersona.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No existen resultados coincidentes", "Atención", JOptionPane.INFORMATION_MESSAGE);
        } else {
            oModeloPersonaJuridica.addAll(listPersona);
        }
        txfBusqRuc.setText("");
        personalizarTabla();
    }

    private void obtenerDatosTabla() {
        beanTabla = (PersonaJuridica) oModeloPersonaJuridica.get(tblResultados.getSelectedRow());

        this.txfRazonSocial.setText(beanTabla.getRazonSocial());
        this.txfNumeroRuc.setText(beanTabla.getNumeroRuc());
        this.txfActividadEconomica.setText(beanTabla.getActividadEcon());
        this.txfDireccion.setText(beanTabla.getDireccion());
        this.txfTelefono.setText(beanTabla.getTelefono());
        if (beanTabla.getProveedors().size() > 0) {
            for (Proveedor bean : beanTabla.getProveedors()) {
                if (bean.getEstado().trim().equals("ACT")) {
                    chbxProveedor.setSelected(true);
                } else {
                    chbxProveedor.setSelected(false);
                }
            }
        } else {
            chbxProveedor.setSelected(false);
        }

    }

    private boolean isDatosValidos() {
        return (!this.txfRazonSocial.getText().trim().equals(""));
    }

    private void cargarDatosPersona() {
        switch (getInvocador()) {
            case JIF_VENTAS:
                //root.jifRegVentas.cargarDatosPersonaJuridica(beanTabla);
                break;
        }
    }

    private void configuraCancelar() {
        resetComponent();
        estadoTextFields(false);
        activarBotones(true, false, false, true);
        oModeloPersonaJuridica.clear();
        oPersonaJuridica = null;
    }

    private void resetComponent() {
        this.txfBusqRuc.setText("");
        this.txfDireccion.setText("");
        this.txfNumeroRuc.setText("");
        this.txfRazonSocial.setText("");
        this.txfTelefono.setText("");
        this.txfActividadEconomica.setText("");
        chbxProveedor.setSelected(false);
    }

    private void estadoTextFields(boolean b) {
        this.txfDireccion.setEnabled(b);
        this.txfNumeroRuc.setEnabled(b);
        this.txfRazonSocial.setEnabled(b);
        this.txfTelefono.setEnabled(b);
        this.txfActividadEconomica.setEnabled(b);
        chbxProveedor.setEnabled(b);
    }

    private void activarBotones(boolean nuevo, boolean modificar, boolean guardar, boolean cancelar) {
        btnNuevo.setEnabled(nuevo);
        btnEditar.setEnabled(modificar);
        btnGuardar.setEnabled(guardar);
        btnCancelar.setEnabled(cancelar);
    }

    public void paintComponent() {
        Utilitarios.paintTxfVacio(txfRazonSocial);
        Utilitarios.paintTxfVacio(txfNumeroRuc);
    }

    private void resetPaintComponent() {
        Utilitarios.resetPaintTxf(txfNumeroRuc);
        Utilitarios.resetPaintTxf(txfRazonSocial);
    }

    private void configuraGuardar() {
        if (banBoton == 1) {
            if (isDatosValidos()) {
                registrar();
                resetComponent();
                estadoTextFields(false);
                resetPaintComponent();
                buscarPersonaJuridica();
            } else {
                JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos", "ATENCION", JOptionPane.INFORMATION_MESSAGE);
                paintComponent();
            }

        } else if (banBoton == 2) {
            if (isDatosValidos()) {
                actualizar();
                //buscar por razon social y listar en la tabla
                buscarPersonaJuridicaxNombre(txfRazonSocial.getText().toUpperCase().trim());
                //resetear componentes
                resetComponent();
                estadoTextFields(false);
                resetPaintComponent();
                //buscarPersonaJuridica();
            } else {
                JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos", "ATENCION", JOptionPane.INFORMATION_MESSAGE);
                paintComponent();
            }

        }
    }

    private void registrar() {
        oPersonaJuridica = registrarEmpresa();
        if (oPersonaJuridica != null) {
            //Registrar si esta empresa es proveedor
            if (oPersonaJuridica != null && chbxProveedor.isSelected()) {
                oProveedor = registrarProveedor();
            }
            Mensajes.msjRegCorrecta();
        } else {
            Mensajes.msjRegError();
        }
//        registrarEmpresa();
//        if(registrarPersonaEmpresa() != null){
//            JOptionPane.showMessageDialog(null, Mensajes.getRegCorrecto(), Mensajes.getTituloAtencion(), JOptionPane.INFORMATION_MESSAGE);
//        }        
    }

    private void actualizar() {
        //actualizarPersona();
        int res = actualizarPersonaJuridica();
        if (res == 1) {
            actualizarProveedor();
            Mensajes.msjActCorrecta();
        } else {
            Mensajes.msjActErronea();
        }
        //actualizarPersonaEmpresa();
    }

    private void configuraNuevo() {
        banBoton = 1;
        tblResultados.setEnabled(true);
        oModeloPersonaJuridica.clear();
        resetComponent();
        estadoTextFields(true);
        activarBotones(false, false, true, true);
    }

    private void configuraActualizar() {
        banBoton = 2;
        estadoTextFields(true);
        activarBotones(true, false, true, true);
    }

    private void personalizarTabla() {
        Utilitarios.formateaColumna(0, tblResultados, 50);
        Utilitarios.formateaColumna(2, tblResultados, 100);
    }

    public int getInvocador() {
        return invocador;
    }

    public void setInvocador(int invocador) {
        this.invocador = invocador;
    }

    private PersonaJuridica registrarEmpresa() {
        oPersonaJuridica = new PersonaJuridica();
        oPersonaJuridicaBl = new PersonaJuridicaBl();

        oPersonaJuridica.setRazonSocial(txfRazonSocial.getText().trim().toUpperCase());
        oPersonaJuridica.setNumeroRuc(txfNumeroRuc.getText().trim().toUpperCase());
        oPersonaJuridica.setActividadEcon(txfActividadEconomica.getText().trim().toUpperCase());
        oPersonaJuridica.setDireccion(txfDireccion.getText().trim().toUpperCase());
        oPersonaJuridica.setTelefono(txfTelefono.getText().trim().toUpperCase());

        //
        PersonaJuridica temp = oPersonaJuridicaBl.buscarxRuc(oPersonaJuridica.getNumeroRuc());
        if (temp != null) {
            Mensajes.msjExisteRegistro();
            return null;
        } else {
            oPersonaJuridica = oPersonaJuridicaBl.registrar(oPersonaJuridica);
            return oPersonaJuridica;
        }

    }

    private Proveedor registrarProveedor() {
        oProveedor = new Proveedor();
        oProveedorBl = new ProveedorBl();

        oProveedor.setPersonaJuridica(oPersonaJuridica);
        oProveedor.setEstado("ACT");

        return oProveedorBl.registrar(oProveedor);
    }

    private PersonaEmpresa registrarPersonaEmpresa() {
        oPersonaEmpresa = new PersonaEmpresa();
        oPersonaEmpresaBl = new PersonaEmpresaBl();

        oPersonaEmpresa.setPersona(oPersona);
        oPersonaEmpresa.setPersonaJuridica(oPersonaJuridica);
        oPersonaEmpresa.setFechaRegistro(new Date());

        oPersonaEmpresa = oPersonaEmpresaBl.registrar(oPersonaEmpresa);
        return oPersonaEmpresa;
    }

    private PersonaEmpresa buscarPersonaEmpresa(int id) {
        oPersonaEmpresaBl = new PersonaEmpresaBl();
        return oPersonaEmpresaBl.buscarXidPersJur(id);
    }

    private Persona buscarRepresentante(int id) {
        oPersonaBl = new PersonaBl();
        return oPersonaBl.buscarPersonaXid(id);
    }

    private int actualizarPersonaJuridica() {
        oPersonaJuridica = new PersonaJuridica();
        oPersonaJuridicaBl = new PersonaJuridicaBl();

        oPersonaJuridica.setIdPersonaJuridica(beanTabla.getIdPersonaJuridica());
        oPersonaJuridica.setRazonSocial(txfRazonSocial.getText().trim().toUpperCase());
        oPersonaJuridica.setNumeroRuc(txfNumeroRuc.getText().trim().toUpperCase());
        oPersonaJuridica.setActividadEcon(txfActividadEconomica.getText().trim().toUpperCase());
        oPersonaJuridica.setDireccion(txfDireccion.getText().trim().toUpperCase());
        oPersonaJuridica.setTelefono(txfTelefono.getText().trim().toUpperCase());

        return oPersonaJuridicaBl.actualizar(oPersonaJuridica);
    }

    private void actualizarPersonaEmpresa() {
        //oPersonaEmpresa = new PersonaEmpresa();
        oPersonaEmpresaBl = new PersonaEmpresaBl();
        int res = 0;
        oPersonaEmpresa.setPersona(oPersona);
        oPersonaEmpresa.setPersonaJuridica(oPersonaJuridica);

        res = oPersonaEmpresaBl.actualizar(oPersonaEmpresa);
        if (res == PersonaEmpresaDao.SUCCESS) {
            JOptionPane.showMessageDialog(null, Mensajes.getActCorrecto(), Mensajes.getTituloAtencion(), JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, Mensajes.getActError(), Mensajes.getTituloAtencion(), JOptionPane.ERROR_MESSAGE);
        }
    }

    private void buscarPersonaJuridicaRuc() {
        oPersonaJuridica = new PersonaJuridica();
        oPersonaJuridicaBl = new PersonaJuridicaBl();
        oPersonaJuridica = oPersonaJuridicaBl.buscarxRuc(txfBusqRuc.getText().trim());
        if (oPersonaJuridica != null) {
            oModeloPersonaJuridica.add(oPersonaJuridica);
        } else {
            Mensajes.msjResultVacio();
        }
        personalizarTabla();
    }

    private void buscarPersonaJuridicaxNombre() {
        oPersonaJuridicaBl = new PersonaJuridicaBl();
        String ref = txfBusqRazonSocial.getText().trim().toUpperCase();
        listPersona = oPersonaJuridicaBl.buscarPersonaJuridica(ref);
        if (!listPersona.isEmpty()) {
            oModeloPersonaJuridica.addAll(listPersona);
        } else {
            Mensajes.msjResultVacio();
        }
        personalizarTabla();
    }

    private void buscarPersonaJuridicaxNombre(String nombre) {
        oPersonaJuridicaBl = new PersonaJuridicaBl();
        listPersona = oPersonaJuridicaBl.buscarPersonaJuridica(nombre);
        if (!listPersona.isEmpty()) {
            oModeloPersonaJuridica.addAll(listPersona);
        } else {
            Mensajes.msjResultVacio();
        }
        personalizarTabla();
    }

    private void actualizarProveedor() {
        oProveedor = new Proveedor();
        oProveedorBl = new ProveedorBl();
        if (beanTabla.getProveedors().isEmpty()) {
            oProveedor.setPersonaJuridica(beanTabla);
            oProveedor.setEstado("ACT");
            oProveedorBl.registrar(oProveedor);
        } else {
            for (Proveedor obj : beanTabla.getProveedors()) {
                oProveedor.setIdproveedor(obj.getIdproveedor());
            }
            oProveedor.setPersonaJuridica(beanTabla);
            if (chbxProveedor.isSelected()) {
                oProveedor.setEstado("ACT");
            } else {
                oProveedor.setEstado("ANU");
            }
            oProveedorBl.actualizar(oProveedor);
        }

    }
}
