package lissa.util;

import org.openfact.client.OpenfactClientFactory;
import org.openfact.client.OrganizationClient;
import org.openfact.client.oauth.TokenManager;
import org.openfact.client.services.DocumentsService;

public class OpenFact {

    public static final String openfactUrl = "http://openfactv2-openfact-development.apps.console.sistcoop.org:83/api";
    public static final String tokenServerUrl = "http://keycloak-keycloak-sso-development.apps.console.sistcoop.org:83/auth/realms/ahren/protocol/openid-connect/token";
    public static final String refreshToken = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJGSjg2R2NGM2pUYk5MT2NvNE52WmtVQ0lVbWZZQ3FvcXRPUWVNZmJoTmxFIn0.eyJqdGkiOiJhZDEyMzIzNS0wYWEyLTQ2Y2QtYmVhZS00NDExYTU4M2EyZGQiLCJleHAiOjAsIm5iZiI6MCwiaWF0IjoxNTM3Mjg4NjQwLCJpc3MiOiJodHRwOi8va2V5Y2xvYWsta2V5Y2xvYWstc3NvLWRldmVsb3BtZW50LmFwcHMuY29uc29sZS5zaXN0Y29vcC5vcmc6ODMvYXV0aC9yZWFsbXMvYWhyZW4iLCJhdWQiOiJvcGVuZmFjdC13ZWItY29uc29sZSIsInN1YiI6IjdiNjdlM2VlLTRlOGYtNDhhYi05YWFhLTRkOWI1ZDIzMWE4NyIsInR5cCI6Ik9mZmxpbmUiLCJhenAiOiJvcGVuZmFjdC13ZWItY29uc29sZSIsIm5vbmNlIjoiYWMxMjQ0MmYtM2RlZC00OTkyLTgwMGItMGE3Yzg3NWE1YjAzIiwiYXV0aF90aW1lIjowLCJzZXNzaW9uX3N0YXRlIjoiZjQ2OWY2YjctOThiOC00YTkxLWJkMzQtNzhmNzRmY2M5ODI5IiwiY2xpZW50X3Nlc3Npb24iOiI1NDMyNzAyMS1kZTA5LTQ0OGItYjU5ZC00MTJkZTkyOTVjNDYiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJvcmdhbml6YXRpb24tdXNlciJdfSwicmVzb3VyY2VfYWNjZXNzIjp7Im9wZW5mYWN0Ijp7InJvbGVzIjpbInZpZXctZXZlbnRzIiwidmlldy1kb2N1bWVudHMiLCJtYW5hZ2UtZG9jdW1lbnRzIl19LCJhY2NvdW50Ijp7InJvbGVzIjpbInZpZXctcHJvZmlsZSJdfX19.lmp19CCHVxwBX0GItszYDjD_1CyJHIUpSLzQ3me_vlzJ4-1nRzGy1eKDPGFzt08EJXNznVNEQEAOqV_C_ULUmyeaDNLqpvhS0MIVaC1G2gwriWTVYgokkbNfuHRJtXfawce7wzwCzmDZLlsv-k6BZeGHwNQAObZle20ToaMhEjw";

    TokenManager tokenManager = OpenfactClientFactory.getTokenManager("openfact-web-console", tokenServerUrl, refreshToken);
    DocumentsService service = OpenfactClientFactory.getDocumentsService(openfactUrl, tokenManager);
    OrganizationClient client = new OrganizationClient("miempresa", service);

}
