/*
BASE DE DATOS
*/
--
ALTER TABLE PERSONA
      ALTER COLUMN APELLIDO_PATERNO TYPE VARCHAR(100);
-----------------------------------------------------
ALTER TABLE COMPROBANTE
ADD COLUMN ID_USUARIOANU BIGINT,
ADD COLUMN CORREO_CLIENTE_TEMP VARCHAR(100) DEFAULT '' NOT NULL,
ADD COLUMN ESTADO_SUNAT VARCHAR(30) DEFAULT '' NOT NULL


